/* Generated by: FreeCC 0.9.3. Do not edit. AdditiveExpression.java */
package org.owasp.orizon.mirage.java.parser;

public class AdditiveExpression extends Expression {
    public AdditiveExpression(int id) {
        super(id);
    }

    public AdditiveExpression() {
        super(JavaConstants.ADDITIVEEXPRESSION);
    }

}
