/* Generated by: FreeCC 0.9.3. Do not edit. AllocationExpression.java */
package org.owasp.orizon.mirage.java.parser;

public class AllocationExpression extends BaseNode {
    public AllocationExpression(int id) {
        super(id);
    }

    public AllocationExpression() {
        super(JavaConstants.ALLOCATIONEXPRESSION);
    }

}
