/* Generated by: FreeCC 0.9.3. Do not edit. AndExpression.java */
package org.owasp.orizon.mirage.java.parser;

public class AndExpression extends Expression {
    public AndExpression(int id) {
        super(id);
    }

    public AndExpression() {
        super(JavaConstants.ANDEXPRESSION);
    }

}
