/* Generated by: FreeCC 0.9.3. Do not edit. AnnotationTypeMemberDeclaration.java */
package org.owasp.orizon.mirage.java.parser;

public class AnnotationTypeMemberDeclaration extends BaseNode {
    public AnnotationTypeMemberDeclaration(int id) {
        super(id);
    }

    public AnnotationTypeMemberDeclaration() {
        super(JavaConstants.ANNOTATIONTYPEMEMBERDECLARATION);
    }

}
