/* Generated by: FreeCC 0.9.3. Do not edit. AnnotationTypeBody.java */
package org.owasp.orizon.mirage.java.parser;

public class AnnotationTypeBody extends BaseNode {
    public AnnotationTypeBody(int id) {
        super(id);
    }

    public AnnotationTypeBody() {
        super(JavaConstants.ANNOTATIONTYPEBODY);
    }

}
