/* Generated by: FreeCC 0.9.3. Do not edit. Annotation.java */
package org.owasp.orizon.mirage.java.parser;

public class Annotation extends BaseNode {
    public Annotation(int id) {
        super(id);
    }

    public Annotation() {
        super(JavaConstants.ANNOTATION);
    }

}
