/* Generated by: FreeCC 0.9.3. Do not edit. ArrayDimsAndInits.java */
package org.owasp.orizon.mirage.java.parser;

public class ArrayDimsAndInits extends BaseNode {
    public ArrayDimsAndInits(int id) {
        super(id);
    }

    public ArrayDimsAndInits() {
        super(JavaConstants.ARRAYDIMSANDINITS);
    }

}
