/* Generated by: FreeCC 0.9.3. Do not edit. ArrayInitializer.java */
package org.owasp.orizon.mirage.java.parser;

public class ArrayInitializer extends BaseNode {
    public ArrayInitializer(int id) {
        super(id);
    }

    public ArrayInitializer() {
        super(JavaConstants.ARRAYINITIALIZER);
    }

}
