/* Generated by: FreeCC 0.9.3. Do not edit. AssertStatement.java */
package org.owasp.orizon.mirage.java.parser;

public class AssertStatement extends BaseNode {
    public AssertStatement(int id) {
        super(id);
    }

    public AssertStatement() {
        super(JavaConstants.ASSERTSTATEMENT);
    }

}
