/* Generated by: FreeCC 0.9.3. Do not edit. AssignmentExpression.java */
package org.owasp.orizon.mirage.java.parser;

public class AssignmentExpression extends Expression {
    public AssignmentExpression(int id) {
        super(id);
    }

    public AssignmentExpression() {
        super(JavaConstants.ASSIGNMENTEXPRESSION);
    }

}
