/* Generated by: FreeCC 0.9.3. Do not edit. BreakStatement.java */
package org.owasp.orizon.mirage.java.parser;

public class BreakStatement extends BaseNode {
    public BreakStatement(int id) {
        super(id);
    }

    public BreakStatement() {
        super(JavaConstants.BREAKSTATEMENT);
    }

}
