/* Generated by: FreeCC 0.9.3. Do not edit. CastExpression.java */
package org.owasp.orizon.mirage.java.parser;

public class CastExpression extends Expression {
    public CastExpression(int id) {
        super(id);
    }

    public CastExpression() {
        super(JavaConstants.CASTEXPRESSION);
    }

}
