/* Generated by: FreeCC 0.9.3. Do not edit. CastLookahead.java */
package org.owasp.orizon.mirage.java.parser;

public class CastLookahead extends BaseNode {
    public CastLookahead(int id) {
        super(id);
    }

    public CastLookahead() {
        super(JavaConstants.CASTLOOKAHEAD);
    }

}
