/* Generated by: FreeCC 0.9.3. Do not edit. CatchBlock.java */
package org.owasp.orizon.mirage.java.parser;

public class CatchBlock extends BaseNode {
    public CodeBlock getBlock() {
        return Nodes.firstChildOfType(this,CodeBlock.class);
    }

    public CatchBlock(int id) {
        super(id);
    }

    public CatchBlock() {
        super(JavaConstants.CATCHBLOCK);
    }

}
