/* Generated by: FreeCC 0.9.3. Do not edit. ClassDeclaration.java */
package org.owasp.orizon.mirage.java.parser;

public class ClassDeclaration extends BaseNode {
    public ClassDeclaration(int id) {
        super(id);
    }

    public ClassDeclaration() {
        super(JavaConstants.CLASSDECLARATION);
    }

}
