/* Generated by: FreeCC 0.9.3. Do not edit. ClassOrInterfaceBodyDeclaration.java */
package org.owasp.orizon.mirage.java.parser;

public class ClassOrInterfaceBodyDeclaration extends BaseNode {
    public boolean isMethod() {
        return Nodes.firstChildOfType(this,MethodDeclaration.class)!=null;
    }

    public String getFullNameSignatureIfMethod() {
        MethodDeclaration md=Nodes.firstChildOfType(this,MethodDeclaration.class);
        return md==null?null:
        md.getFullSignature();
    }

    public ClassOrInterfaceBodyDeclaration(int id) {
        super(id);
    }

    public ClassOrInterfaceBodyDeclaration() {
        super(JavaConstants.CLASSORINTERFACEBODYDECLARATION);
    }

}
