/* Generated by: FreeCC 0.9.3. Do not edit. CodeBlock.java */
package org.owasp.orizon.mirage.java.parser;

public class CodeBlock extends BaseNode {
    public String getAsString() {
        return getInnerText();
    }

    /**
     * The block is empty if it only consists of { and }
     */
    public boolean isEmpty() {
        return Nodes.getRealTokens(this).size()==2;
    }

    public CodeBlock(int id) {
        super(id);
    }

    public CodeBlock() {
        super(JavaConstants.CODEBLOCK);
    }

}
