/* Generated by: FreeCC 0.9.3. Do not edit. Comment.java */
package org.owasp.orizon.mirage.java.parser;

public class Comment extends Token {
    public Comment(int kind,String image) {
        super(kind,image);
    }

}
