/* Generated by: FreeCC 0.9.3. Do not edit. ConditionalAndExpression.java */
package org.owasp.orizon.mirage.java.parser;

public class ConditionalAndExpression extends Expression {
    public ConditionalAndExpression(int id) {
        super(id);
    }

    public ConditionalAndExpression() {
        super(JavaConstants.CONDITIONALANDEXPRESSION);
    }

}
