/* Generated by: FreeCC 0.9.3. Do not edit. ConditionalOrExpression.java */
package org.owasp.orizon.mirage.java.parser;

public class ConditionalOrExpression extends Expression {
    public ConditionalOrExpression(int id) {
        super(id);
    }

    public ConditionalOrExpression() {
        super(JavaConstants.CONDITIONALOREXPRESSION);
    }

}
