/* Generated by: FreeCC 0.9.3. Do not edit. ConstructorDeclaration.java */
package org.owasp.orizon.mirage.java.parser;

public class ConstructorDeclaration extends BaseNode {
    public ConstructorDeclaration(int id) {
        super(id);
    }

    public ConstructorDeclaration() {
        super(JavaConstants.CONSTRUCTORDECLARATION);
    }

}
