/* Generated by: FreeCC 0.9.3. Do not edit. ContinueStatement.java */
package org.owasp.orizon.mirage.java.parser;

public class ContinueStatement extends BaseNode {
    public ContinueStatement(int id) {
        super(id);
    }

    public ContinueStatement() {
        super(JavaConstants.CONTINUESTATEMENT);
    }

}
