/* Generated by: FreeCC 0.9.3. Do not edit. DefaultValue.java */
package org.owasp.orizon.mirage.java.parser;

public class DefaultValue extends BaseNode {
    public DefaultValue(int id) {
        super(id);
    }

    public DefaultValue() {
        super(JavaConstants.DEFAULTVALUE);
    }

}
