/* Generated by: FreeCC 0.9.3. Do not edit. Delimiter.java */
package org.owasp.orizon.mirage.java.parser;

public class Delimiter extends Token {
    public Delimiter(int kind,String image) {
        super(kind,image);
    }

}
