/* Generated by: FreeCC 0.9.3. Do not edit. DoStatement.java */
package org.owasp.orizon.mirage.java.parser;

public class DoStatement extends BaseNode {
    public DoStatement(int id) {
        super(id);
    }

    public DoStatement() {
        super(JavaConstants.DOSTATEMENT);
    }

}
