/* Generated by: FreeCC 0.9.3. Do not edit. EmptyStatement.java */
package org.owasp.orizon.mirage.java.parser;

public class EmptyStatement extends BaseNode {
    public EmptyStatement(int id) {
        super(id);
    }

    public EmptyStatement() {
        super(JavaConstants.EMPTYSTATEMENT);
    }

}
