/* Generated by: FreeCC 0.9.3. Do not edit. EnumConstant.java */
package org.owasp.orizon.mirage.java.parser;

public class EnumConstant extends BaseNode {
    public EnumConstant(int id) {
        super(id);
    }

    public EnumConstant() {
        super(JavaConstants.ENUMCONSTANT);
    }

}
