/* Generated by: FreeCC 0.9.3. Do not edit. EnumBody.java */
package org.owasp.orizon.mirage.java.parser;

public class EnumBody extends BaseNode {
    public EnumBody(int id) {
        super(id);
    }

    public EnumBody() {
        super(JavaConstants.ENUMBODY);
    }

}
