/* Generated by: FreeCC 0.9.3. Do not edit. EqualityExpression.java */
package org.owasp.orizon.mirage.java.parser;

public class EqualityExpression extends Expression {
    public EqualityExpression(int id) {
        super(id);
    }

    public EqualityExpression() {
        super(JavaConstants.EQUALITYEXPRESSION);
    }

}
