/* Generated by: FreeCC 0.9.3. Do not edit. ExclusiveOrExpression.java */
package org.owasp.orizon.mirage.java.parser;

public class ExclusiveOrExpression extends Expression {
    public ExclusiveOrExpression(int id) {
        super(id);
    }

    public ExclusiveOrExpression() {
        super(JavaConstants.EXCLUSIVEOREXPRESSION);
    }

}
