/* Generated by: FreeCC 0.9.3. Do not edit. Expression.java */
package org.owasp.orizon.mirage.java.parser;

public class Expression extends BaseNode {
    public Expression(int id) {
        super(id);
    }

    public Expression() {
        super(JavaConstants.EXPRESSION);
    }

}
