/* Generated by: FreeCC 0.9.3. Do not edit. ExtendsList.java */
package org.owasp.orizon.mirage.java.parser;

import java.util.*;
public class ExtendsList extends BaseNode {
    public List<ObjectType>getTypes() {
        return Nodes.childrenOfType(this,ObjectType.class);
    }

    public void addType(ObjectType type,boolean isInterface) {
        if (!isInterface) {
            children=new java.util.ArrayList<Node>();
        }
        ListIterator<Node>iterator=iterator();
        if (!iterator.hasNext()) {
            iterator.add(Token.newToken(EXTENDS,"extends"));
            iterator.next();
            iterator.add(type);
        }
        else {
            while (iterator.hasNext()) {
                if (type.equals(iterator.next())) return;
            }
            iterator.add(Token.newToken(COMMA,","));
            iterator.next();
            iterator.add(type);
        }
    }

    public ExtendsList(int id) {
        super(id);
    }

    public ExtendsList() {
        super(JavaConstants.EXTENDSLIST);
    }

}
