/* Generated by: FreeCC 0.9.3. Do not edit. FieldDeclaration.java */
package org.owasp.orizon.mirage.java.parser;

public class FieldDeclaration extends BaseNode {
    public FieldDeclaration(int id) {
        super(id);
    }

    public FieldDeclaration() {
        super(JavaConstants.FIELDDECLARATION);
    }

}
