/* Generated by: FreeCC 0.9.3. Do not edit. FinallyBlock.java */
package org.owasp.orizon.mirage.java.parser;

public class FinallyBlock extends BaseNode {
    public CodeBlock getBlock() {
        return Nodes.firstChildOfType(this,CodeBlock.class);
    }

    public FinallyBlock(int id) {
        super(id);
    }

    public FinallyBlock() {
        super(JavaConstants.FINALLYBLOCK);
    }

}
