/* Generated by: FreeCC 0.9.3. Do not edit. ForInit.java */
package org.owasp.orizon.mirage.java.parser;

public class ForInit extends BaseNode {
    public ForInit(int id) {
        super(id);
    }

    public ForInit() {
        super(JavaConstants.FORINIT);
    }

}
