/* Generated by: FreeCC 0.9.3. Do not edit. FormalParameter.java */
package org.owasp.orizon.mirage.java.parser;

public class FormalParameter extends BaseNode {
    public FormalParameter(int id) {
        super(id);
    }

    public FormalParameter() {
        super(JavaConstants.FORMALPARAMETER);
    }

}
