/* Generated by: FreeCC 0.9.3. Do not edit. FormalParams.java */
package org.owasp.orizon.mirage.java.parser;

import java.util.List;
public class FormalParams extends BaseNode {
    public List<FormalParameter>getParams() {
        return Nodes.childrenOfType(this,FormalParameter.class);
    }

    public String getAsString() {
        StringBuilder buf=new StringBuilder();
        List<FormalParameter>params=getParams();
        boolean first=true;
        for(FormalParameter param : params) {
            if (!first) {
                buf.append(", ");
            }
            buf.append(param.getAsString());
            first=false;
        }
        return buf.toString();
    }

    public String toString() {
        StringBuilder buf=new StringBuilder();
        for(Token tok : Nodes.getRealTokens(this)) {
            buf.append(" ");
            buf.append(tok);
        }
        return buf.toString();
    }

    public FormalParams(int id) {
        super(id);
    }

    public FormalParams() {
        super(JavaConstants.FORMALPARAMS);
    }

}
