/* Generated by: FreeCC 0.9.3. Do not edit. ForStatement.java */
package org.owasp.orizon.mirage.java.parser;

public class ForStatement extends BaseNode {
    public ForStatement(int id) {
        super(id);
    }

    public ForStatement() {
        super(JavaConstants.FORSTATEMENT);
    }

}
