/* Generated by: FreeCC 0.9.3. Do not edit. ForUpdate.java */
package org.owasp.orizon.mirage.java.parser;

public class ForUpdate extends BaseNode {
    public ForUpdate(int id) {
        super(id);
    }

    public ForUpdate() {
        super(JavaConstants.FORUPDATE);
    }

}
