/* Generated by: FreeCC 0.9.3. Do not edit. Identifier.java */
package org.owasp.orizon.mirage.java.parser;

public class Identifier extends Token {
    public Identifier(int kind,String image) {
        super(kind,image);
    }

}
