/* Generated by: FreeCC 0.9.3. Do not edit. IfStatement.java */
package org.owasp.orizon.mirage.java.parser;

public class IfStatement extends BaseNode {
    public IfStatement(int id) {
        super(id);
    }

    public IfStatement() {
        super(JavaConstants.IFSTATEMENT);
    }

}
