/* Generated by: FreeCC 0.9.3. Do not edit. ImplementsList.java */
package org.owasp.orizon.mirage.java.parser;

import java.util.*;
public class ImplementsList extends BaseNode {
    public List<ObjectType>getTypes() {
        return Nodes.childrenOfType(this,ObjectType.class);
    }

    public void addType(ObjectType type) {
        ListIterator<Node>iterator=iterator();
        if (!iterator.hasNext()) {
            iterator.add(Token.newToken(IMPLEMENTS,"implements"));
            iterator.next();
            iterator.add(type);
        }
        else {
            while (iterator.hasNext()) {
                if (type.equals(iterator.next())) return;
            }
            iterator.add(Token.newToken(COMMA,","));
            iterator.next();
            iterator.add(type);
        }
    }

    public ImplementsList(int id) {
        super(id);
    }

    public ImplementsList() {
        super(JavaConstants.IMPLEMENTSLIST);
    }

}
