/* Generated by: FreeCC 0.9.3. Do not edit. ImportDeclaration.java */
package org.owasp.orizon.mirage.java.parser;

public class ImportDeclaration extends BaseNode {
    public String getAsString() {
        return super.getAsString().trim();
    }

    public boolean isStaticImport() {
        for(Node n : children) {
            if (n.getId()==STATIC) {
                return true;
            }
        }
        return false;
    }

    public String getName() {
        StringBuilder buf=new StringBuilder();
        for(Token tok : Nodes.getRealTokens(this)) {
            if (tok.getId()!=IMPORT&&tok.getId()!=SEMICOLON) {
                buf.append(tok);
            }
        }
        return buf.toString();
    }

    public boolean equals(Object obj) {
        if (!(obj instanceof ImportDeclaration)) {
            return false;
        }
        ImportDeclaration other=(ImportDeclaration) obj;
        return other.isStaticImport()==this.isStaticImport()&&other.getName().equals(this.getName());
    }

    public int hashCode() {
        String s=isStaticImport()?"static ":
        "";
        s+=getName();
        return s.hashCode();
    }

    public ImportDeclaration(int id) {
        super(id);
    }

    public ImportDeclaration() {
        super(JavaConstants.IMPORTDECLARATION);
    }

}
