/* Generated by: FreeCC 0.9.3. Do not edit. InclusiveOrExpression.java */
package org.owasp.orizon.mirage.java.parser;

public class InclusiveOrExpression extends Expression {
    public InclusiveOrExpression(int id) {
        super(id);
    }

    public InclusiveOrExpression() {
        super(JavaConstants.INCLUSIVEOREXPRESSION);
    }

}
