/* Generated by: FreeCC 0.9.3. Do not edit. Initializer.java */
package org.owasp.orizon.mirage.java.parser;

public class Initializer extends BaseNode {
    public Initializer(int id) {
        super(id);
    }

    public Initializer() {
        super(JavaConstants.INITIALIZER);
    }

}
