/* Generated by: FreeCC 0.9.3. Do not edit. InstanceOfExpression.java */
package org.owasp.orizon.mirage.java.parser;

public class InstanceOfExpression extends Expression {
    public InstanceOfExpression(int id) {
        super(id);
    }

    public InstanceOfExpression() {
        super(JavaConstants.INSTANCEOFEXPRESSION);
    }

}
