/* Generated by: FreeCC 0.9.3. Do not edit. IntegerLiteral.java */
package org.owasp.orizon.mirage.java.parser;

public class IntegerLiteral extends BaseNode {
    public IntegerLiteral(int id) {
        super(id);
    }

    public IntegerLiteral() {
        super(JavaConstants.INTEGERLITERAL);
    }

}
