/* Generated by: FreeCC 0.9.3. Do not edit. InterfaceDeclaration.java */
package org.owasp.orizon.mirage.java.parser;

public class InterfaceDeclaration extends BaseNode {
    /**
     * Returns the interface's name.
     * 
     * @return the interface's name.
     */
    public String getName() {
        StringBuilder buf=new StringBuilder();
        // Since an interface is supposed to extends something
        // a WHITESPACE char is the delimiter between the name
        // and the extends clause.
        // 
        // FIXME: a malformed interface declaration can cause an
        // unpredictable behaviour here. Must fix in some way.
        for(Token tok : Nodes.getRealTokens(this)) {
            if (tok.getId()!=INTERFACE) buf.append(tok);
            if (tok.getId()==EXTENDS) break;
        }
        return buf.toString();
    }

    public InterfaceDeclaration(int id) {
        super(id);
    }

    public InterfaceDeclaration() {
        super(JavaConstants.INTERFACEDECLARATION);
    }

}
