/* Generated by: FreeCC 0.9.3. Do not edit. InvocationArgs.java */
package org.owasp.orizon.mirage.java.parser;

import java.util.*;
public class InvocationArgs extends BaseNode {
    public List<Expression>getArgs() {
        return Nodes.childrenOfType(this,Expression.class);
    }

    public String getAsString() {
        StringBuilder buf=new StringBuilder();
        List<Expression>args=getArgs();
        boolean first=true;
        for(Expression arg : args) {
            if (!first) {
                buf.append(", ");
            }
            buf.append(arg.getAsString());
            first=false;
        }
        return buf.toString();
    }

    public InvocationArgs(int id) {
        super(id);
    }

    public InvocationArgs() {
        super(JavaConstants.INVOCATIONARGS);
    }

}
