/* Generated by: FreeCC 0.9.3. JavaLexer.java */
package org.owasp.orizon.mirage.java.parser;

/** Token Manager */
@SuppressWarnings("unused")
public class JavaLexer implements JavaConstants {
    int angleBracketNesting=0;
    private Token tokenHook(Token t) {
        Token result=t;
        if (angleBracketNesting>0&&t.image.length()>1&&t.image.charAt(0)=='>') {
            int amountToBackUp=t.image.length()-1;
            input_stream.backup(amountToBackUp);
            t.endColumn-=amountToBackUp;
            result=new org.owasp.orizon.mirage.java.parser.Operator(JavaConstants.GT,">");
            Nodes.copyLocationInfo(t,result);
            result.setEndColumn(t.getEndColumn()-amountToBackUp);
        }
        return result;
    }

    /** Debug output. */
    java.io.PrintStream debugStream=System.out;
    /** Set debug output. */
    public void setDebugStream(java.io.PrintStream ds) {
        debugStream=ds;
    }

    int[] jjemptyLineNo=new int[4];
    int[] jjemptyColNo=new int[4];
    boolean[] jjbeenHere=new boolean[4];
    int curLexState;
    int jjnewStateCnt;
    int jjround;
    int jjmatchedPos;
    int jjmatchedKind;
    private String inputSource="input";
    public String getInputSource() {
        return inputSource;
    }

    public void setInputSource(String inputSource) {
        this.inputSource=inputSource;
    }

    static final String[] lexStateNames={"DEFAULT","IN_SINGLE_LINE_COMMENT","IN_FORMAL_COMMENT","IN_MULTI_LINE_COMMENT",};
    /** Lex State array. */
    public static final int[] jjnewLexState={-1,-1,1,2,3,0,0,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,};
    // Bit vector for TOKEN
    static final long[] jjtoToken={0x7ffffffffffffe01L,0x3ffffffffffff84L,};
    // Bit vector for SKIP
    static final long[] jjtoSkip={0xe2L,0x0L,};
    // Bit vector for SPECIAL
    static final long[] jjtoSpecial={0xe2L,0x0L,};
    // Bit vector for MORE
    static final long[] jjtoMore={0x11cL,0x0L,};
    JavaCharStream input_stream;
    private final int[] jjrounds=new int[66];
    private final int[] jjstateSet=new int[132];
    private final StringBuffer jjimage=new StringBuffer();
    private StringBuffer image=jjimage;
    private int jjimageLen;
    char curChar;
    /** Constructor. */
    public JavaLexer(JavaCharStream stream) {
        input_stream=stream;
    }

    /** Constructor. */
    public JavaLexer(JavaCharStream stream,int lexState) {
        this(stream);
        SwitchTo(lexState);
    }

    // Method to reinitialize the jjrounds array.
    private void ReInitRounds() {
        int i;
        jjround=0x80000001;
        for(i=66; 
        i-->0; 
        ) jjrounds[i]=0x80000000; 
    }

    /** Switch to specified lex state. */
    public void SwitchTo(int lexState) {
        if (lexState>=4||lexState<0) throw new LexicalException("Error: Ignoring invalid lexical state : "+lexState+". State unchanged.",LexicalException.INVALID_LEXICAL_STATE);
        else curLexState=lexState;
    }

    /** Get the next Token. */
    public Token getNextToken() {
        Token specialToken=null;
        Token matchedToken;
        int curPos=0;
        EOFLoop:
        while (true) {
            try {
                curChar=input_stream.BeginToken();
            }
            catch(java.io.IOException e) {
                jjmatchedKind=0;
                matchedToken=jjFillToken();
                matchedToken=tokenHook(matchedToken);
                matchedToken.specialToken=specialToken;
                return matchedToken;
            }
            image=jjimage;
            image.setLength(0);
            jjimageLen=0;
            while (true) {
                switch(curLexState) {
                    case 0:
                    jjmatchedKind=0x7FFFFFFF;
                    jjmatchedPos=0;
                    curPos=jjMoveStringLiteralDfa0();
                    break;
                    case 1:
                    jjmatchedKind=0x7FFFFFFF;
                    jjmatchedPos=0;
                    curPos=jjMoveStringLiteralDfa0_IN_SINGLE_LINE_COMMENT();
                    break;
                    case 2:
                    jjmatchedKind=0x7FFFFFFF;
                    jjmatchedPos=0;
                    curPos=jjMoveStringLiteralDfa0_IN_FORMAL_COMMENT();
                    break;
                    case 3:
                    jjmatchedKind=0x7FFFFFFF;
                    jjmatchedPos=0;
                    curPos=jjMoveStringLiteralDfa0_IN_MULTI_LINE_COMMENT();
                    break;
                }
                if (jjmatchedKind!=0x7FFFFFFF) {
                    if (jjmatchedPos+1<curPos) input_stream.backup(curPos-jjmatchedPos-1);
                    if ((jjtoToken[jjmatchedKind>>6]&(1L<<(jjmatchedKind&077)))!=0L) {
                        matchedToken=jjFillToken();
                        matchedToken=tokenHook(matchedToken);
                        matchedToken.specialToken=specialToken;
                        TokenLexicalActions(matchedToken);
                        jjmatchedKind=matchedToken.kind;
                        if (jjnewLexState[jjmatchedKind]!=-1) {
                            curLexState=jjnewLexState[jjmatchedKind];
                        }
                        return matchedToken;
                    }
                    else if ((jjtoSkip[jjmatchedKind>>6]&(1L<<(jjmatchedKind&077)))!=0L) {
                        if ((jjtoSpecial[jjmatchedKind>>6]&(1L<<(jjmatchedKind&077)))!=0L) {
                            matchedToken=jjFillToken();
                            matchedToken.setUnparsed(true);
                            if (specialToken==null) {
                                specialToken=matchedToken;
                            }
                            else {
                                matchedToken.specialToken=specialToken;
                                specialToken=(specialToken.next=matchedToken);
                            }
                            TokenLexicalActions(matchedToken);
                        }
                        else TokenLexicalActions(null);
                        if (jjnewLexState[jjmatchedKind]!=-1) curLexState=jjnewLexState[jjmatchedKind];
                        continue EOFLoop;
                    }
                    TokenLexicalActions(null);
                    if (jjnewLexState[jjmatchedKind]!=-1) curLexState=jjnewLexState[jjmatchedKind];
                    curPos=0;
                    jjmatchedKind=0x7FFFFFFF;
                    try {
                        curChar=input_stream.readChar();
                        continue;
                    }
                    catch(java.io.IOException e1) {
                    }
                }
                int error_line=input_stream.getEndLine();
                int error_column=input_stream.getEndColumn();
                String error_after=null;
                boolean EOFSeen=false;
                try {
                    input_stream.readChar();
                    input_stream.backup(1);
                }
                catch(java.io.IOException e1) {
                    EOFSeen=true;
                    error_after=curPos<=1?"":
                    input_stream.GetImage();
                    if (curChar=='\n'||curChar=='\r') {
                        error_line++;
                        error_column=0;
                    }
                    else error_column++;
                }
                if (!EOFSeen) {
                    input_stream.backup(1);
                    error_after=curPos<=1?"":
                    input_stream.GetImage();
                }
                throw new LexicalException(EOFSeen,curLexState,error_line,error_column,error_after,curChar,inputSource,LexicalException.LEXICAL_ERROR);
            }
        }
    }

    void TokenLexicalActions(Token matchedToken) {
        switch(jjmatchedKind) {
            case 3:
            image.append(input_stream.GetSuffix(jjimageLen+jjmatchedPos+1));
            input_stream.backup(1);
            break;
            default:
            break;
        }
    }

    Token jjFillToken() {
        final Token t;
        final String curTokenImage;
        final int beginLine;
        final int endLine;
        final int beginColumn;
        final int endColumn;
        curTokenImage=input_stream.GetImage();
        beginLine=input_stream.getBeginLine();
        beginColumn=input_stream.getBeginColumn();
        endLine=input_stream.getEndLine();
        endColumn=input_stream.getEndColumn();
        t=Token.newToken(jjmatchedKind,curTokenImage);
        t.beginLine=beginLine;
        t.endLine=endLine;
        t.beginColumn=beginColumn;
        t.endColumn=endColumn;
        t.setInputSource(this.inputSource);
        return t;
    }

    private void jjCheckNAdd(int state) {
        if (jjrounds[state]!=jjround) {
            jjstateSet[jjnewStateCnt++]=state;
            jjrounds[state]=jjround;
        }
    }

    private void jjAddStates(int start,int end) {
        do {
            jjstateSet[jjnewStateCnt++]=jjnextStates[start];
        }
        while (start++!=end);
    }

    private void jjCheckNAddTwoStates(int state1,int state2) {
        jjCheckNAdd(state1);
        jjCheckNAdd(state2);
    }

    private void jjCheckNAddStates(int start,int end) {
        do {
            jjCheckNAdd(jjnextStates[start]);
        }
        while (start++!=end);
    }

    private void jjCheckNAddStates(int start) {
        jjCheckNAdd(jjnextStates[start]);
        jjCheckNAdd(jjnextStates[start+1]);
    }

    private static boolean jjCanMove_0(int hiByte,int i1,int i2,long l1,long l2) {
        switch(hiByte) {
            case 0:
            return(jjbitVec2[i2]&l2)!=0L;
            default:
            if ((jjbitVec0[i1]&l1)!=0L) {
                return(jjbitVec1[i2]&l2)!=0L;
            }
            return false;
        }
    }

    private static boolean jjCanMove_1(int hiByte,int i1,int i2,long l1,long l2) {
        switch(hiByte) {
            case 0:
            return(jjbitVec4[i2]&l2)!=0L;
            case 2:
            return(jjbitVec5[i2]&l2)!=0L;
            case 3:
            return(jjbitVec6[i2]&l2)!=0L;
            case 4:
            return(jjbitVec7[i2]&l2)!=0L;
            case 5:
            return(jjbitVec8[i2]&l2)!=0L;
            case 6:
            return(jjbitVec9[i2]&l2)!=0L;
            case 7:
            return(jjbitVec10[i2]&l2)!=0L;
            case 9:
            return(jjbitVec11[i2]&l2)!=0L;
            case 10:
            return(jjbitVec12[i2]&l2)!=0L;
            case 11:
            return(jjbitVec13[i2]&l2)!=0L;
            case 12:
            return(jjbitVec14[i2]&l2)!=0L;
            case 13:
            return(jjbitVec15[i2]&l2)!=0L;
            case 14:
            return(jjbitVec16[i2]&l2)!=0L;
            case 15:
            return(jjbitVec17[i2]&l2)!=0L;
            case 16:
            return(jjbitVec18[i2]&l2)!=0L;
            case 17:
            return(jjbitVec19[i2]&l2)!=0L;
            case 18:
            return(jjbitVec20[i2]&l2)!=0L;
            case 19:
            return(jjbitVec21[i2]&l2)!=0L;
            case 20:
            return(jjbitVec22[i2]&l2)!=0L;
            case 22:
            return(jjbitVec23[i2]&l2)!=0L;
            case 23:
            return(jjbitVec24[i2]&l2)!=0L;
            case 24:
            return(jjbitVec25[i2]&l2)!=0L;
            case 30:
            return(jjbitVec26[i2]&l2)!=0L;
            case 31:
            return(jjbitVec27[i2]&l2)!=0L;
            case 32:
            return(jjbitVec28[i2]&l2)!=0L;
            case 33:
            return(jjbitVec29[i2]&l2)!=0L;
            case 48:
            return(jjbitVec30[i2]&l2)!=0L;
            case 49:
            return(jjbitVec31[i2]&l2)!=0L;
            case 77:
            return(jjbitVec32[i2]&l2)!=0L;
            case 159:
            return(jjbitVec33[i2]&l2)!=0L;
            case 164:
            return(jjbitVec34[i2]&l2)!=0L;
            case 215:
            return(jjbitVec35[i2]&l2)!=0L;
            case 250:
            return(jjbitVec36[i2]&l2)!=0L;
            case 251:
            return(jjbitVec37[i2]&l2)!=0L;
            case 253:
            return(jjbitVec38[i2]&l2)!=0L;
            case 254:
            return(jjbitVec39[i2]&l2)!=0L;
            case 255:
            return(jjbitVec40[i2]&l2)!=0L;
            default:
            if ((jjbitVec3[i1]&l1)!=0L) {
                return(jjbitVec1[i2]&l2)!=0L;
            }
            return false;
        }
    }

    private static boolean jjCanMove_2(int hiByte,int i1,int i2,long l1,long l2) {
        switch(hiByte) {
            case 0:
            return(jjbitVec41[i2]&l2)!=0L;
            case 2:
            return(jjbitVec5[i2]&l2)!=0L;
            case 3:
            return(jjbitVec42[i2]&l2)!=0L;
            case 4:
            return(jjbitVec43[i2]&l2)!=0L;
            case 5:
            return(jjbitVec44[i2]&l2)!=0L;
            case 6:
            return(jjbitVec45[i2]&l2)!=0L;
            case 7:
            return(jjbitVec46[i2]&l2)!=0L;
            case 9:
            return(jjbitVec47[i2]&l2)!=0L;
            case 10:
            return(jjbitVec48[i2]&l2)!=0L;
            case 11:
            return(jjbitVec49[i2]&l2)!=0L;
            case 12:
            return(jjbitVec50[i2]&l2)!=0L;
            case 13:
            return(jjbitVec51[i2]&l2)!=0L;
            case 14:
            return(jjbitVec52[i2]&l2)!=0L;
            case 15:
            return(jjbitVec53[i2]&l2)!=0L;
            case 16:
            return(jjbitVec54[i2]&l2)!=0L;
            case 17:
            return(jjbitVec19[i2]&l2)!=0L;
            case 18:
            return(jjbitVec20[i2]&l2)!=0L;
            case 19:
            return(jjbitVec55[i2]&l2)!=0L;
            case 20:
            return(jjbitVec22[i2]&l2)!=0L;
            case 22:
            return(jjbitVec23[i2]&l2)!=0L;
            case 23:
            return(jjbitVec56[i2]&l2)!=0L;
            case 24:
            return(jjbitVec57[i2]&l2)!=0L;
            case 30:
            return(jjbitVec26[i2]&l2)!=0L;
            case 31:
            return(jjbitVec27[i2]&l2)!=0L;
            case 32:
            return(jjbitVec58[i2]&l2)!=0L;
            case 33:
            return(jjbitVec29[i2]&l2)!=0L;
            case 48:
            return(jjbitVec59[i2]&l2)!=0L;
            case 49:
            return(jjbitVec31[i2]&l2)!=0L;
            case 77:
            return(jjbitVec32[i2]&l2)!=0L;
            case 159:
            return(jjbitVec33[i2]&l2)!=0L;
            case 164:
            return(jjbitVec34[i2]&l2)!=0L;
            case 215:
            return(jjbitVec35[i2]&l2)!=0L;
            case 250:
            return(jjbitVec36[i2]&l2)!=0L;
            case 251:
            return(jjbitVec60[i2]&l2)!=0L;
            case 253:
            return(jjbitVec38[i2]&l2)!=0L;
            case 254:
            return(jjbitVec61[i2]&l2)!=0L;
            case 255:
            return(jjbitVec62[i2]&l2)!=0L;
            default:
            if ((jjbitVec3[i1]&l1)!=0L) {
                return(jjbitVec1[i2]&l2)!=0L;
            }
            return false;
        }
    }

    private int jjStopAtPos(int pos,int kind) {
        jjmatchedKind=kind;
        jjmatchedPos=pos;
        return pos+1;
    }

    static final long[] jjbitVec0={0xfffffffffffffffeL,0xffffffffffffffffL,0xffffffffffffffffL,0xffffffffffffffffL};
    static final long[] jjbitVec1={0xffffffffffffffffL,0xffffffffffffffffL,0xffffffffffffffffL,0xffffffffffffffffL};
    static final long[] jjbitVec2={0x0L,0x0L,0xffffffffffffffffL,0xffffffffffffffffL};
    static final long[] jjbitVec3={0xfff0000000200002L,0xffffffffffffdfffL,0xfffff00f7fffffffL,0x12000000007fffffL};
    static final long[] jjbitVec4={0x0L,0x0L,0x420043c00000000L,0xff7fffffff7fffffL};
    static final long[] jjbitVec5={0xffffcffffffffL,0xffffffffffff0000L,0xf9ff3fffffffffffL,0x401f00030003L};
    static final long[] jjbitVec6={0x0L,0x400000000000000L,0xfffffffbffffd740L,0xffffffcff7fffL};
    static final long[] jjbitVec7={0xffffffffffffffffL,0xffffffffffffffffL,0xfffffffffffff003L,0x33fffffffff199fL};
    static final long[] jjbitVec8={0xfffe000000000000L,0xfffffffe027fffffL,0xffL,0x707ffffff0000L};
    static final long[] jjbitVec9={0x7fffffe00000000L,0xfffe0000000007ffL,0xffffffffffffffffL,0x1c000060002fffffL};
    static final long[] jjbitVec10={0x1ffffffd0000L,0x0L,0x3fffffffffL,0x0L};
    static final long[] jjbitVec11={0x23ffffffffffffe0L,0x3ff010000L,0x3c5fdfffff99fe0L,0xf0003b0000000L};
    static final long[] jjbitVec12={0x36dfdfffff987e0L,0x1c00005e000000L,0x23edfdfffffbafe0L,0x100010000L};
    static final long[] jjbitVec13={0x23cdfdfffff99fe0L,0x3b0000000L,0x3bfc718d63dc7e0L,0x0L};
    static final long[] jjbitVec14={0x3effdfffffddfe0L,0x300000000L,0x3effdfffffddfe0L,0x340000000L};
    static final long[] jjbitVec15={0x3fffdfffffddfe0L,0x300000000L,0x2ffbfffffc7fffe0L,0x7fL};
    static final long[] jjbitVec16={0x800dfffffffffffeL,0x7fL,0x200decaefef02596L,0x3000005fL};
    static final long[] jjbitVec17={0x1L,0x7fffffffeffL,0xf00L,0x0L};
    static final long[] jjbitVec18={0x6fbffffffffL,0x3f0000L,0xffffffff00000000L,0x7fffffffff003fL};
    static final long[] jjbitVec19={0xffffffffffffffffL,0xffffffff83ffffffL,0xffffff07ffffffffL,0x3ffffffffffffffL};
    static final long[] jjbitVec20={0xffffffffffffff7fL,0xffffffff3d7f3d7fL,0x7f3d7fffffff3d7fL,0xffff7fffff7f7f3dL};
    static final long[] jjbitVec21={0xffffffff7f3d7fffL,0x7ffff7fL,0xffffffff00000000L,0x1fffffffffffffL};
    static final long[] jjbitVec22={0xfffffffffffffffeL,0xffffffffffffffffL,0xffffffffffffffffL,0xffffffffffffffffL};
    static final long[] jjbitVec23={0xffffffffffffffffL,0x7f9fffffffffffL,0xffffffff07fffffeL,0x7ffffffffffL};
    static final long[] jjbitVec24={0x0L,0x0L,0xfffffffffffffL,0x8000000L};
    static final long[] jjbitVec25={0xffffffff00000000L,0xffffffffffffffL,0x1ffffffffffL,0x0L};
    static final long[] jjbitVec26={0xffffffffffffffffL,0xffffffffffffffffL,0xffffffff0fffffffL,0x3ffffffffffffffL};
    static final long[] jjbitVec27={0xffffffff3f3fffffL,0x3fffffffaaff3f3fL,0x5fdfffffffffffffL,0x1fdc1fff0fcf1fdcL};
    static final long[] jjbitVec28={0x8000000000000000L,0x8000000000000001L,0xffff00000000L,0x0L};
    static final long[] jjbitVec29={0x3fbbd503e2ffc84L,0xffffffff00000000L,0xfL,0x0L};
    static final long[] jjbitVec30={0x73e03fe000000e0L,0xfffffffffffffffeL,0xfffffffe601fffffL,0x7fffffffffffffffL};
    static final long[] jjbitVec31={0xfffe1fffffffffe0L,0xffffffffffffffffL,0xffffff00007fffL,0x0L};
    static final long[] jjbitVec32={0xffffffffffffffffL,0xffffffffffffffffL,0x3fffffffffffffL,0x0L};
    static final long[] jjbitVec33={0xffffffffffffffffL,0xffffffffffffffffL,0x3fffffffffL,0x0L};
    static final long[] jjbitVec34={0xffffffffffffffffL,0xffffffffffffffffL,0x1fffL,0x0L};
    static final long[] jjbitVec35={0xffffffffffffffffL,0xffffffffffffffffL,0xfffffffffL,0x0L};
    static final long[] jjbitVec36={0x3fffffffffffL,0x0L,0x0L,0x0L};
    static final long[] jjbitVec37={0x5f7ffdffa0f8007fL,0xffffffffffffffdbL,0x3ffffffffffffL,0xfffffffffff80000L};
    static final long[] jjbitVec38={0x3fffffffffffffffL,0xffffffffffff0000L,0xfffffffffffcffffL,0xfff0000000000ffL};
    static final long[] jjbitVec39={0x18000000000000L,0xffd702000000e000L,0xffffffffffffffffL,0x1fffffffffffffffL};
    static final long[] jjbitVec40={0x87fffffe00000010L,0xffffffe007fffffeL,0x7fffffffffffffffL,0x631cfcfcfcL};
    static final long[] jjbitVec41={0x0L,0x0L,0x420043cffffffffL,0xff7fffffff7fffffL};
    static final long[] jjbitVec42={0xffffffffffffffffL,0x400000700007fffL,0xfffffffbffffd740L,0xffffffcff7fffL};
    static final long[] jjbitVec43={0xffffffffffffffffL,0xffffffffffffffffL,0xfffffffffffff07bL,0x33fffffffff199fL};
    static final long[] jjbitVec44={0xfffe000000000000L,0xfffffffe027fffffL,0xbbfffffbfffe00ffL,0x707ffffff0016L};
    static final long[] jjbitVec45={0x7fffffe00000000L,0xffff03ff003fffffL,0xffffffffffffffffL,0x1fff3dff9fefffffL};
    static final long[] jjbitVec46={0xffff1fffffff8000L,0x7ffL,0x1ffffffffffffL,0x0L};
    static final long[] jjbitVec47={0xf3ffffffffffffeeL,0xffcfff1f3fffL,0xd3c5fdfffff99feeL,0xfffcfb080399fL};
    static final long[] jjbitVec48={0xd36dfdfffff987e4L,0x1fffc05e003987L,0xf3edfdfffffbafeeL,0xffc100013bbfL};
    static final long[] jjbitVec49={0xf3cdfdfffff99feeL,0xffc3b0c0398fL,0xc3bfc718d63dc7ecL,0xff8000803dc7L};
    static final long[] jjbitVec50={0xc3effdfffffddfeeL,0xffc300603ddfL,0xc3effdfffffddfecL,0xffc340603ddfL};
    static final long[] jjbitVec51={0xc3fffdfffffddfecL,0xffc300803dcfL,0x2ffbfffffc7fffecL,0xc0000ff5f847fL};
    static final long[] jjbitVec52={0x87fffffffffffffeL,0x3ff7fffL,0x3bffecaefef02596L,0x33ff3f5fL};
    static final long[] jjbitVec53={0xc2a003ff03000001L,0xfffe07fffffffeffL,0x1ffffffffeff0fdfL,0x40L};
    static final long[] jjbitVec54={0x3c7f6fbffffffffL,0x3ff03ffL,0xffffffff00000000L,0x7fffffffff003fL};
    static final long[] jjbitVec55={0xffffffff7f3d7fffL,0x3fe0007ffff7fL,0xffffffff00000000L,0x1fffffffffffffL};
    static final long[] jjbitVec56={0x0L,0x0L,0xffffffffffffffffL,0x3ff080fffffL};
    static final long[] jjbitVec57={0xffffffff03ff7800L,0xffffffffffffffL,0x3ffffffffffL,0x0L};
    static final long[] jjbitVec58={0x80007c000000f000L,0x8000fc0000000001L,0xffff00000000L,0x21fff0000L};
    static final long[] jjbitVec59={0x73efffe000000e0L,0xfffffffffffffffeL,0xfffffffe661fffffL,0x7fffffffffffffffL};
    static final long[] jjbitVec60={0x5f7ffdffe0f8007fL,0xffffffffffffffdbL,0x3ffffffffffffL,0xfffffffffff80000L};
    static final long[] jjbitVec61={0x18000f00000000L,0xffd702000000e000L,0xffffffffffffffffL,0x9fffffffffffffffL};
    static final long[] jjbitVec62={0x87fffffe03ff0010L,0xffffffe007fffffeL,0x7fffffffffffffffL,0xe0000631cfcfcfcL};
    private int jjStartNfa(int pos,long active0,long active1) {
        return jjMoveNfa(jjStopStringLiteralDfa(pos,active0,active1),pos+1);
    }

    private final int jjStopStringLiteralDfa(int pos,long active0,long active1) {
        switch(pos) {
            case 0:
            if ((active0&0x14L)!=0L||(active1&0x801000000000L)!=0L) return 3;
            if ((active1&0x80000000020000L)!=0L) return 9;
            if ((active0&0x3ffffffffffffe00L)!=0L) {
                jjmatchedKind=121;
                return 33;
            }
            return-1;
            case 1:
            if ((active0&0x3ffffffeff9ffe00L)!=0L) {
                if (jjmatchedPos!=1) {
                    jjmatchedKind=121;
                    jjmatchedPos=1;
                }
                return 33;
            }
            if ((active0&0x10L)!=0L) return 1;
            if ((active0&0x100600000L)!=0L) return 33;
            return-1;
            case 2:
            if ((active0&0x3bfffecebfdffe00L)!=0L) {
                if (jjmatchedPos!=2) {
                    jjmatchedKind=121;
                    jjmatchedPos=2;
                }
                return 33;
            }
            if ((active0&0x400013040000000L)!=0L) return 33;
            return-1;
            case 3:
            if ((active0&0x31dffcae3e5e9e00L)!=0L) {
                jjmatchedKind=121;
                jjmatchedPos=3;
                return 33;
            }
            if ((active0&0xa20024081816000L)!=0L) return 33;
            return-1;
            case 4:
            if ((active0&0x111b7cae02580e00L)!=0L) {
                if (jjmatchedPos!=4) {
                    jjmatchedKind=121;
                    jjmatchedPos=4;
                }
                return 33;
            }
            if ((active0&0x20c480003c069000L)!=0L) return 33;
            return-1;
            case 5:
            if ((active0&0x11121c2a12180a00L)!=0L) {
                jjmatchedKind=121;
                jjmatchedPos=5;
                return 33;
            }
            if ((active0&0x89608400400400L)!=0L) return 33;
            return-1;
            case 6:
            if ((active0&0x1112102a00080200L)!=0L) {
                jjmatchedKind=121;
                jjmatchedPos=6;
                return 33;
            }
            if ((active0&0xc0012100800L)!=0L) return 33;
            return-1;
            case 7:
            if ((active0&0x110102a00000000L)!=0L) {
                jjmatchedKind=121;
                jjmatchedPos=7;
                return 33;
            }
            if ((active0&0x1002000000080200L)!=0L) return 33;
            return-1;
            case 8:
            if ((active0&0x10000a00000000L)!=0L) {
                jjmatchedKind=121;
                jjmatchedPos=8;
                return 33;
            }
            if ((active0&0x100102000000000L)!=0L) return 33;
            return-1;
            case 9:
            if ((active0&0x10000000000000L)!=0L) {
                jjmatchedKind=121;
                jjmatchedPos=9;
                return 33;
            }
            if ((active0&0xa00000000L)!=0L) return 33;
            return-1;
            case 10:
            if ((active0&0x10000000000000L)!=0L) {
                jjmatchedKind=121;
                jjmatchedPos=10;
                return 33;
            }
            return-1;
            case 11:
            if ((active0&0x10000000000000L)!=0L) return 33;
            return-1;
            default:
            return-1;
        }
    }

    private int jjStartNfaWithStates(int pos,int kind,int state) {
        jjmatchedKind=kind;
        jjmatchedPos=pos;
        try {
            curChar=input_stream.readChar();
        }
        catch(java.io.IOException e) {
            return pos+1;
        }
        return jjMoveNfa(state,pos+1);
    }

    private int jjMoveStringLiteralDfa0() {
        switch(curChar) {
            case 33:
            jjmatchedKind=85;
            return jjMoveStringLiteralDfa1(0x0L,0x10000000L);
            case 37:
            jjmatchedKind=104;
            return jjMoveStringLiteralDfa1(0x0L,0x8000000000000L);
            case 38:
            jjmatchedKind=101;
            return jjMoveStringLiteralDfa1(0x0L,0x1000040000000L);
            case 40:
            return jjStopAtPos(0,73);
            case 41:
            return jjStopAtPos(0,74);
            case 42:
            jjmatchedKind=99;
            return jjMoveStringLiteralDfa1(0x0L,0x400000000000L);
            case 43:
            jjmatchedKind=97;
            return jjMoveStringLiteralDfa1(0x0L,0x100080000000L);
            case 44:
            return jjStopAtPos(0,80);
            case 45:
            jjmatchedKind=98;
            return jjMoveStringLiteralDfa1(0x0L,0x200100000000L);
            case 46:
            jjmatchedKind=81;
            return jjMoveStringLiteralDfa1(0x0L,0x80000000000000L);
            case 47:
            jjmatchedKind=100;
            return jjMoveStringLiteralDfa1(0x14L,0x800000000000L);
            case 58:
            return jjStopAtPos(0,88);
            case 59:
            return jjStopAtPos(0,79);
            case 60:
            jjmatchedKind=84;
            return jjMoveStringLiteralDfa1(0x0L,0x10020004000000L);
            case 61:
            jjmatchedKind=82;
            return jjMoveStringLiteralDfa1(0x0L,0x2000000L);
            case 62:
            jjmatchedKind=83;
            return jjMoveStringLiteralDfa1(0x0L,0x600c0008000000L);
            case 63:
            return jjStopAtPos(0,87);
            case 64:
            return jjStopAtPos(0,120);
            case 91:
            return jjStopAtPos(0,77);
            case 93:
            return jjStopAtPos(0,78);
            case 94:
            jjmatchedKind=103;
            return jjMoveStringLiteralDfa1(0x0L,0x4000000000000L);
            case 97:
            return jjMoveStringLiteralDfa1(0x600L,0x0L);
            case 98:
            return jjMoveStringLiteralDfa1(0x3800L,0x0L);
            case 99:
            return jjMoveStringLiteralDfa1(0xfc000L,0x0L);
            case 100:
            return jjMoveStringLiteralDfa1(0x700000L,0x0L);
            case 101:
            return jjMoveStringLiteralDfa1(0x3800000L,0x0L);
            case 102:
            return jjMoveStringLiteralDfa1(0x7c000000L,0x0L);
            case 103:
            return jjMoveStringLiteralDfa1(0x80000000L,0x0L);
            case 105:
            return jjMoveStringLiteralDfa1(0x3f00000000L,0x0L);
            case 108:
            return jjMoveStringLiteralDfa1(0x4000000000L,0x0L);
            case 110:
            return jjMoveStringLiteralDfa1(0x38000000000L,0x0L);
            case 112:
            return jjMoveStringLiteralDfa1(0x3c0000000000L,0x0L);
            case 114:
            return jjMoveStringLiteralDfa1(0x400000000000L,0x0L);
            case 115:
            return jjMoveStringLiteralDfa1(0x1f800000000000L,0x0L);
            case 116:
            return jjMoveStringLiteralDfa1(0x7e0000000000000L,0x0L);
            case 118:
            return jjMoveStringLiteralDfa1(0x1800000000000000L,0x0L);
            case 119:
            return jjMoveStringLiteralDfa1(0x2000000000000000L,0x0L);
            case 123:
            return jjStopAtPos(0,75);
            case 124:
            jjmatchedKind=102;
            return jjMoveStringLiteralDfa1(0x0L,0x2000020000000L);
            case 125:
            return jjStopAtPos(0,76);
            case 126:
            return jjStopAtPos(0,86);
            default:
            return jjMoveNfa(4,0);
        }
    }

    private int jjMoveStringLiteralDfa1(long active0,long active1) {
        try {
            curChar=input_stream.readChar();
        }
        catch(java.io.IOException e) {
            jjStopStringLiteralDfa(0,active0,active1);
            return 1;
        }
        switch(curChar) {
            case 38:
            if ((active1&0x40000000L)!=0L) return jjStopAtPos(1,94);
            break;
            case 42:
            if ((active0&0x10L)!=0L) return jjStartNfaWithStates(1,4,1);
            break;
            case 43:
            if ((active1&0x80000000L)!=0L) return jjStopAtPos(1,95);
            break;
            case 45:
            if ((active1&0x100000000L)!=0L) return jjStopAtPos(1,96);
            break;
            case 46:
            return jjMoveStringLiteralDfa2(active0,0x0L,active1,0x80000000000000L);
            case 47:
            if ((active0&0x4L)!=0L) return jjStopAtPos(1,2);
            break;
            case 60:
            if ((active1&0x20000000000L)!=0L) {
                jjmatchedKind=105;
                jjmatchedPos=1;
            }
            return jjMoveStringLiteralDfa2(active0,0x0L,active1,0x10000000000000L);
            case 61:
            if ((active1&0x2000000L)!=0L) return jjStopAtPos(1,89);
            else if ((active1&0x4000000L)!=0L) return jjStopAtPos(1,90);
            else if ((active1&0x8000000L)!=0L) return jjStopAtPos(1,91);
            else if ((active1&0x10000000L)!=0L) return jjStopAtPos(1,92);
            else if ((active1&0x100000000000L)!=0L) return jjStopAtPos(1,108);
            else if ((active1&0x200000000000L)!=0L) return jjStopAtPos(1,109);
            else if ((active1&0x400000000000L)!=0L) return jjStopAtPos(1,110);
            else if ((active1&0x800000000000L)!=0L) return jjStopAtPos(1,111);
            else if ((active1&0x1000000000000L)!=0L) return jjStopAtPos(1,112);
            else if ((active1&0x2000000000000L)!=0L) return jjStopAtPos(1,113);
            else if ((active1&0x4000000000000L)!=0L) return jjStopAtPos(1,114);
            else if ((active1&0x8000000000000L)!=0L) return jjStopAtPos(1,115);
            break;
            case 62:
            if ((active1&0x40000000000L)!=0L) {
                jjmatchedKind=106;
                jjmatchedPos=1;
            }
            return jjMoveStringLiteralDfa2(active0,0x0L,active1,0x60080000000000L);
            case 97:
            return jjMoveStringLiteralDfa2(active0,0x4800400c000L,active1,0x0L);
            case 98:
            return jjMoveStringLiteralDfa2(active0,0x200L,active1,0x0L);
            case 101:
            return jjMoveStringLiteralDfa2(active0,0x410000100000L,active1,0x0L);
            case 102:
            if ((active0&0x100000000L)!=0L) return jjStartNfaWithStates(1,32,33);
            break;
            case 104:
            return jjMoveStringLiteralDfa2(active0,0x20e0800000010000L,active1,0x0L);
            case 105:
            return jjMoveStringLiteralDfa2(active0,0x18000000L,active1,0x0L);
            case 108:
            return jjMoveStringLiteralDfa2(active0,0x20820000L,active1,0x0L);
            case 109:
            return jjMoveStringLiteralDfa2(active0,0x600000000L,active1,0x0L);
            case 110:
            return jjMoveStringLiteralDfa2(active0,0x3801000000L,active1,0x0L);
            case 111:
            if ((active0&0x200000L)!=0L) {
                jjmatchedKind=21;
                jjmatchedPos=1;
            }
            return jjMoveStringLiteralDfa2(active0,0x18000040c04c0800L,active1,0x0L);
            case 114:
            return jjMoveStringLiteralDfa2(active0,0x700180000001000L,active1,0x0L);
            case 115:
            return jjMoveStringLiteralDfa2(active0,0x400L,active1,0x0L);
            case 116:
            return jjMoveStringLiteralDfa2(active0,0x3000000000000L,active1,0x0L);
            case 117:
            return jjMoveStringLiteralDfa2(active0,0x4220000000000L,active1,0x0L);
            case 119:
            return jjMoveStringLiteralDfa2(active0,0x8000000000000L,active1,0x0L);
            case 120:
            return jjMoveStringLiteralDfa2(active0,0x2000000L,active1,0x0L);
            case 121:
            return jjMoveStringLiteralDfa2(active0,0x10000000002000L,active1,0x0L);
            case 124:
            if ((active1&0x20000000L)!=0L) return jjStopAtPos(1,93);
            break;
            default:
            break;
        }
        return jjStartNfa(0,active0,active1);
    }

    private int jjMoveStringLiteralDfa2(long old0,long active0,long old1,long active1) {
        active0=active0&old0;
        active1=active1&old1;
        if ((active0|active1)==0L) return jjStartNfa(0,old0,old1);
        try {
            curChar=input_stream.readChar();
        }
        catch(java.io.IOException e) {
            jjStopStringLiteralDfa(1,active0,active1);
            return 2;
        }
        switch(curChar) {
            case 46:
            if ((active1&0x80000000000000L)!=0L) return jjStopAtPos(2,119);
            break;
            case 61:
            if ((active1&0x10000000000000L)!=0L) return jjStopAtPos(2,116);
            else if ((active1&0x20000000000000L)!=0L) return jjStopAtPos(2,117);
            break;
            case 62:
            if ((active1&0x80000000000L)!=0L) {
                jjmatchedKind=107;
                jjmatchedPos=2;
            }
            return jjMoveStringLiteralDfa3(active0,0x0L,active1,0x40000000000000L);
            case 97:
            return jjMoveStringLiteralDfa3(active0,0x101000000030000L,active1,0x0L);
            case 98:
            return jjMoveStringLiteralDfa3(active0,0x200000000000L,active1,0x0L);
            case 99:
            return jjMoveStringLiteralDfa3(active0,0x40000000000L,active1,0x0L);
            case 101:
            return jjMoveStringLiteralDfa3(active0,0x1000L,active1,0x0L);
            case 102:
            return jjMoveStringLiteralDfa3(active0,0x100000L,active1,0x0L);
            case 105:
            return jjMoveStringLiteralDfa3(active0,0x2828080000000000L,active1,0x0L);
            case 108:
            return jjMoveStringLiteralDfa3(active0,0x1000020004000000L,active1,0x0L);
            case 110:
            return jjMoveStringLiteralDfa3(active0,0x100040180c0000L,active1,0x0L);
            case 111:
            return jjMoveStringLiteralDfa3(active0,0x900020000800L,active1,0x0L);
            case 112:
            return jjMoveStringLiteralDfa3(active0,0x4000600000000L,active1,0x0L);
            case 114:
            if ((active0&0x40000000L)!=0L) return jjStartNfaWithStates(2,30,33);
            return jjMoveStringLiteralDfa3(active0,0xc2000000000000L,active1,0x0L);
            case 115:
            return jjMoveStringLiteralDfa3(active0,0x800804600L,active1,0x0L);
            case 116:
            if ((active0&0x1000000000L)!=0L) {
                jjmatchedKind=36;
                jjmatchedPos=2;
            }
            return jjMoveStringLiteralDfa3(active0,0x40a08200a000L,active1,0x0L);
            case 117:
            return jjMoveStringLiteralDfa3(active0,0x200000001400000L,active1,0x0L);
            case 119:
            if ((active0&0x10000000000L)!=0L) return jjStartNfaWithStates(2,40,33);
            break;
            case 121:
            if ((active0&0x400000000000000L)!=0L) return jjStartNfaWithStates(2,58,33);
            break;
            default:
            break;
        }
        return jjStartNfa(1,active0,active1);
    }

    private int jjMoveStringLiteralDfa3(long old0,long active0,long old1,long active1) {
        active0=active0&old0;
        active1=active1&old1;
        if ((active0|active1)==0L) return jjStartNfa(1,old0,old1);
        try {
            curChar=input_stream.readChar();
        }
        catch(java.io.IOException e) {
            jjStopStringLiteralDfa(2,active0,active1);
            return 3;
        }
        switch(curChar) {
            case 61:
            if ((active1&0x40000000000000L)!=0L) return jjStopAtPos(3,118);
            break;
            case 97:
            return jjMoveStringLiteralDfa4(active0,0x1000000038101000L,active1,0x0L);
            case 98:
            return jjMoveStringLiteralDfa4(active0,0x400000L,active1,0x0L);
            case 99:
            return jjMoveStringLiteralDfa4(active0,0x10000000008000L,active1,0x0L);
            case 100:
            if ((active0&0x800000000000000L)!=0L) return jjStartNfaWithStates(3,59,33);
            break;
            case 101:
            if ((active0&0x2000L)!=0L) return jjStartNfaWithStates(3,13,33);
            else if ((active0&0x4000L)!=0L) return jjStartNfaWithStates(3,14,33);
            else if ((active0&0x800000L)!=0L) return jjStartNfaWithStates(3,23,33);
            else if ((active0&0x200000000000000L)!=0L) return jjStartNfaWithStates(3,57,33);
            return jjMoveStringLiteralDfa4(active0,0x4002002000400L,active1,0x0L);
            case 103:
            if ((active0&0x4000000000L)!=0L) return jjStartNfaWithStates(3,38,33);
            break;
            case 105:
            return jjMoveStringLiteralDfa4(active0,0x2008000000000L,active1,0x0L);
            case 107:
            return jjMoveStringLiteralDfa4(active0,0x40000000000L,active1,0x0L);
            case 108:
            if ((active0&0x20000000000L)!=0L) return jjStartNfaWithStates(3,41,33);
            return jjMoveStringLiteralDfa4(active0,0x2000200200000800L,active1,0x0L);
            case 109:
            if ((active0&0x1000000L)!=0L) return jjStartNfaWithStates(3,24,33);
            break;
            case 110:
            return jjMoveStringLiteralDfa4(active0,0x100000000000000L,active1,0x0L);
            case 111:
            if ((active0&0x80000000L)!=0L) return jjStartNfaWithStates(3,31,33);
            return jjMoveStringLiteralDfa4(active0,0xc0000400000000L,active1,0x0L);
            case 114:
            if ((active0&0x10000L)!=0L) return jjStartNfaWithStates(3,16,33);
            return jjMoveStringLiteralDfa4(active0,0x800000000000L,active1,0x0L);
            case 115:
            if ((active0&0x20000000000000L)!=0L) return jjStartNfaWithStates(3,53,33);
            return jjMoveStringLiteralDfa4(active0,0x4060000L,active1,0x0L);
            case 116:
            return jjMoveStringLiteralDfa4(active0,0x9100800080200L,active1,0x0L);
            case 117:
            return jjMoveStringLiteralDfa4(active0,0x400000000000L,active1,0x0L);
            case 118:
            return jjMoveStringLiteralDfa4(active0,0x80000000000L,active1,0x0L);
            default:
            break;
        }
        return jjStartNfa(2,active0,active1);
    }

    private int jjMoveStringLiteralDfa4(long old0,long active0,long old1,long active1) {
        active0=active0&old0;
        active1=active1&old1;
        if ((active0|active1)==0L) return jjStartNfa(2,old0,old1);
        try {
            curChar=input_stream.readChar();
        }
        catch(java.io.IOException e) {
            jjStopStringLiteralDfa(3,active0,0L);
            return 4;
        }
        switch(curChar) {
            case 97:
            return jjMoveStringLiteralDfa5(active0,0xc0800000000L);
            case 99:
            return jjMoveStringLiteralDfa5(active0,0xa000000000000L);
            case 101:
            if ((active0&0x4000000L)!=0L) return jjStartNfaWithStates(4,26,33);
            else if ((active0&0x2000000000000000L)!=0L) return jjStartNfaWithStates(4,61,33);
            return jjMoveStringLiteralDfa5(active0,0x100200000800L);
            case 104:
            if ((active0&0x8000L)!=0L) return jjStartNfaWithStates(4,15,33);
            return jjMoveStringLiteralDfa5(active0,0x10000000000000L);
            case 105:
            return jjMoveStringLiteralDfa5(active0,0x1200000080000L);
            case 107:
            if ((active0&0x1000L)!=0L) return jjStartNfaWithStates(4,12,33);
            break;
            case 108:
            if ((active0&0x8000000L)!=0L) {
                jjmatchedKind=27;
                jjmatchedPos=4;
            }
            return jjMoveStringLiteralDfa5(active0,0x10400000L);
            case 110:
            return jjMoveStringLiteralDfa5(active0,0x2000000L);
            case 114:
            if ((active0&0x4000000000000L)!=0L) return jjStartNfaWithStates(4,50,33);
            return jjMoveStringLiteralDfa5(active0,0x402400000600L);
            case 115:
            if ((active0&0x20000L)!=0L) return jjStartNfaWithStates(4,17,33);
            return jjMoveStringLiteralDfa5(active0,0x100000000000000L);
            case 116:
            if ((active0&0x40000L)!=0L) return jjStartNfaWithStates(4,18,33);
            else if ((active0&0x20000000L)!=0L) return jjStartNfaWithStates(4,29,33);
            else if ((active0&0x800000000000L)!=0L) return jjStartNfaWithStates(4,47,33);
            return jjMoveStringLiteralDfa5(active0,0x1000000000000000L);
            case 117:
            return jjMoveStringLiteralDfa5(active0,0x100000L);
            case 118:
            return jjMoveStringLiteralDfa5(active0,0x8000000000L);
            case 119:
            if ((active0&0x40000000000000L)!=0L) {
                jjmatchedKind=54;
                jjmatchedPos=4;
            }
            return jjMoveStringLiteralDfa5(active0,0x80000000000000L);
            default:
            break;
        }
        return jjStartNfa(3,active0,0L);
    }

    private int jjMoveStringLiteralDfa5(long old0,long active0) {
        active0=active0&old0;
        if ((active0)==0L) return jjStartNfa(3,old0,0L);
        try {
            curChar=input_stream.readChar();
        }
        catch(java.io.IOException e) {
            jjStopStringLiteralDfa(4,active0,0L);
            return 5;
        }
        switch(curChar) {
            case 97:
            return jjMoveStringLiteralDfa6(active0,0xa00L);
            case 99:
            if ((active0&0x200000000000L)!=0L) return jjStartNfaWithStates(5,45,33);
            else if ((active0&0x1000000000000L)!=0L) return jjStartNfaWithStates(5,48,33);
            return jjMoveStringLiteralDfa6(active0,0x100000000000L);
            case 100:
            return jjMoveStringLiteralDfa6(active0,0x2000000L);
            case 101:
            if ((active0&0x400000L)!=0L) return jjStartNfaWithStates(5,22,33);
            else if ((active0&0x8000000000L)!=0L) return jjStartNfaWithStates(5,39,33);
            break;
            case 102:
            return jjMoveStringLiteralDfa6(active0,0x2000000000L);
            case 103:
            return jjMoveStringLiteralDfa6(active0,0x40000000000L);
            case 104:
            if ((active0&0x8000000000000L)!=0L) return jjStartNfaWithStates(5,51,33);
            break;
            case 105:
            return jjMoveStringLiteralDfa6(active0,0x1100000000000000L);
            case 108:
            return jjMoveStringLiteralDfa6(active0,0x10100000L);
            case 109:
            return jjMoveStringLiteralDfa6(active0,0x200000000L);
            case 110:
            if ((active0&0x400000000000L)!=0L) return jjStartNfaWithStates(5,46,33);
            return jjMoveStringLiteralDfa6(active0,0x800080000L);
            case 114:
            return jjMoveStringLiteralDfa6(active0,0x10000000000000L);
            case 115:
            if ((active0&0x80000000000000L)!=0L) return jjStartNfaWithStates(5,55,33);
            break;
            case 116:
            if ((active0&0x400L)!=0L) return jjStartNfaWithStates(5,10,33);
            else if ((active0&0x400000000L)!=0L) return jjStartNfaWithStates(5,34,33);
            return jjMoveStringLiteralDfa6(active0,0x2080000000000L);
            default:
            break;
        }
        return jjStartNfa(4,active0,0L);
    }

    private int jjMoveStringLiteralDfa6(long old0,long active0) {
        active0=active0&old0;
        if ((active0)==0L) return jjStartNfa(4,old0,0L);
        try {
            curChar=input_stream.readChar();
        }
        catch(java.io.IOException e) {
            jjStopStringLiteralDfa(5,active0,0L);
            return 6;
        }
        switch(curChar) {
            case 97:
            return jjMoveStringLiteralDfa7(active0,0x2000000000L);
            case 99:
            return jjMoveStringLiteralDfa7(active0,0x800000200L);
            case 101:
            if ((active0&0x40000000000L)!=0L) return jjStartNfaWithStates(6,42,33);
            else if ((active0&0x80000000000L)!=0L) return jjStartNfaWithStates(6,43,33);
            return jjMoveStringLiteralDfa7(active0,0x100000200000000L);
            case 102:
            return jjMoveStringLiteralDfa7(active0,0x2000000000000L);
            case 108:
            return jjMoveStringLiteralDfa7(active0,0x1000000000000000L);
            case 110:
            if ((active0&0x800L)!=0L) return jjStartNfaWithStates(6,11,33);
            break;
            case 111:
            return jjMoveStringLiteralDfa7(active0,0x10000000000000L);
            case 115:
            if ((active0&0x2000000L)!=0L) return jjStartNfaWithStates(6,25,33);
            break;
            case 116:
            if ((active0&0x100000L)!=0L) return jjStartNfaWithStates(6,20,33);
            return jjMoveStringLiteralDfa7(active0,0x100000000000L);
            case 117:
            return jjMoveStringLiteralDfa7(active0,0x80000L);
            case 121:
            if ((active0&0x10000000L)!=0L) return jjStartNfaWithStates(6,28,33);
            break;
            default:
            break;
        }
        return jjStartNfa(5,active0,0L);
    }

    private int jjMoveStringLiteralDfa7(long old0,long active0) {
        active0=active0&old0;
        if ((active0)==0L) return jjStartNfa(5,old0,0L);
        try {
            curChar=input_stream.readChar();
        }
        catch(java.io.IOException e) {
            jjStopStringLiteralDfa(6,active0,0L);
            return 7;
        }
        switch(curChar) {
            case 99:
            return jjMoveStringLiteralDfa8(active0,0x2000000000L);
            case 101:
            if ((active0&0x80000L)!=0L) return jjStartNfaWithStates(7,19,33);
            else if ((active0&0x1000000000000000L)!=0L) return jjStartNfaWithStates(7,60,33);
            return jjMoveStringLiteralDfa8(active0,0x100800000000L);
            case 110:
            return jjMoveStringLiteralDfa8(active0,0x110000200000000L);
            case 112:
            if ((active0&0x2000000000000L)!=0L) return jjStartNfaWithStates(7,49,33);
            break;
            case 116:
            if ((active0&0x200L)!=0L) return jjStartNfaWithStates(7,9,33);
            break;
            default:
            break;
        }
        return jjStartNfa(6,active0,0L);
    }

    private int jjMoveStringLiteralDfa8(long old0,long active0) {
        active0=active0&old0;
        if ((active0)==0L) return jjStartNfa(6,old0,0L);
        try {
            curChar=input_stream.readChar();
        }
        catch(java.io.IOException e) {
            jjStopStringLiteralDfa(7,active0,0L);
            return 8;
        }
        switch(curChar) {
            case 100:
            if ((active0&0x100000000000L)!=0L) return jjStartNfaWithStates(8,44,33);
            break;
            case 101:
            if ((active0&0x2000000000L)!=0L) return jjStartNfaWithStates(8,37,33);
            break;
            case 105:
            return jjMoveStringLiteralDfa9(active0,0x10000000000000L);
            case 111:
            return jjMoveStringLiteralDfa9(active0,0x800000000L);
            case 116:
            if ((active0&0x100000000000000L)!=0L) return jjStartNfaWithStates(8,56,33);
            return jjMoveStringLiteralDfa9(active0,0x200000000L);
            default:
            break;
        }
        return jjStartNfa(7,active0,0L);
    }

    private int jjMoveStringLiteralDfa9(long old0,long active0) {
        active0=active0&old0;
        if ((active0)==0L) return jjStartNfa(7,old0,0L);
        try {
            curChar=input_stream.readChar();
        }
        catch(java.io.IOException e) {
            jjStopStringLiteralDfa(8,active0,0L);
            return 9;
        }
        switch(curChar) {
            case 102:
            if ((active0&0x800000000L)!=0L) return jjStartNfaWithStates(9,35,33);
            break;
            case 115:
            if ((active0&0x200000000L)!=0L) return jjStartNfaWithStates(9,33,33);
            break;
            case 122:
            return jjMoveStringLiteralDfa10(active0,0x10000000000000L);
            default:
            break;
        }
        return jjStartNfa(8,active0,0L);
    }

    private int jjMoveStringLiteralDfa10(long old0,long active0) {
        active0=active0&old0;
        if ((active0)==0L) return jjStartNfa(8,old0,0L);
        try {
            curChar=input_stream.readChar();
        }
        catch(java.io.IOException e) {
            jjStopStringLiteralDfa(9,active0,0L);
            return 10;
        }
        switch(curChar) {
            case 101:
            return jjMoveStringLiteralDfa11(active0,0x10000000000000L);
            default:
            break;
        }
        return jjStartNfa(9,active0,0L);
    }

    private int jjMoveStringLiteralDfa11(long old0,long active0) {
        active0=active0&old0;
        if ((active0)==0L) return jjStartNfa(9,old0,0L);
        try {
            curChar=input_stream.readChar();
        }
        catch(java.io.IOException e) {
            jjStopStringLiteralDfa(10,active0,0L);
            return 11;
        }
        switch(curChar) {
            case 100:
            if ((active0&0x10000000000000L)!=0L) return jjStartNfaWithStates(11,52,33);
            break;
            default:
            break;
        }
        return jjStartNfa(10,active0,0L);
    }

    private int jjMoveNfa(int startState,int curPos) {
        int startsAt=0;
        jjnewStateCnt=66;
        int i=1;
        jjstateSet[0]=startState;
        int kind=0x7fffffff;
        while (true) {
            if (++jjround==0x7fffffff) {
                ReInitRounds();
            }
            if (curChar<64) {
                long l=1L<<curChar;
                do {
                    switch(jjstateSet[--i]) {
                        case 4:
                        if ((0x3ff000000000000L&l)!=0L) jjAddStates(0,6);
                        else if ((0x100003600L&l)!=0L) {
                            if (kind>1) kind=1;
                            jjCheckNAdd(0);
                        }
                        else if (curChar==36) {
                            if (kind>121) kind=121;
                            jjCheckNAdd(33);
                        }
                        else if (curChar==34) jjCheckNAddStates(7,9);
                        else if (curChar==39) jjAddStates(10,11);
                        else if (curChar==46) jjstateSet[jjnewStateCnt++]=9;
                        else if (curChar==47) jjstateSet[jjnewStateCnt++]=3;
                        if ((0x3fe000000000000L&l)!=0L) {
                            if (kind>62) kind=62;
                            jjAddStates(12,13);
                        }
                        else if (curChar==48) {
                            if (kind>62) kind=62;
                            jjAddStates(14,18);
                        }
                        break;
                        case 0:
                        if ((0x100003600L&l)==0L) break;
                        if (kind>1) kind=1;
                        jjCheckNAdd(0);
                        break;
                        case 1:
                        if (curChar==42) jjstateSet[jjnewStateCnt++]=2;
                        break;
                        case 2:
                        if ((0xffff7fffffffffffL&l)!=0L&&kind>3) kind=3;
                        break;
                        case 3:
                        if (curChar==42) jjstateSet[jjnewStateCnt++]=1;
                        break;
                        case 5:
                        if ((0x3fe000000000000L&l)==0L) break;
                        if (kind>62) kind=62;
                        jjCheckNAddTwoStates(6,7);
                        break;
                        case 6:
                        if ((0x3ff000000000000L&l)==0L) break;
                        if (kind>62) kind=62;
                        jjCheckNAddTwoStates(6,7);
                        break;
                        case 8:
                        if (curChar==46) jjCheckNAdd(9);
                        break;
                        case 9:
                        if ((0x3ff000000000000L&l)==0L) break;
                        if (kind>66) kind=66;
                        jjCheckNAddStates(19,21);
                        break;
                        case 11:
                        if ((0x280000000000L&l)!=0L) jjstateSet[jjnewStateCnt++]=12;
                        break;
                        case 12:
                        if ((0x3ff000000000000L&l)==0L) break;
                        if (kind>66) kind=66;
                        jjCheckNAddTwoStates(12,13);
                        break;
                        case 14:
                        if (curChar==39) jjCheckNAddTwoStates(15,22);
                        break;
                        case 16:
                        if ((0xff000000000000L&l)!=0L) jjCheckNAddTwoStates(17,18);
                        break;
                        case 17:
                        if ((0xff000000000000L&l)!=0L) jjCheckNAdd(18);
                        break;
                        case 18:
                        if (curChar==39&&kind>71) kind=71;
                        break;
                        case 19:
                        if ((0xf000000000000L&l)!=0L) jjstateSet[jjnewStateCnt++]=20;
                        break;
                        case 20:
                        if ((0xff000000000000L&l)!=0L) jjstateSet[jjnewStateCnt++]=17;
                        break;
                        case 21:
                        if ((0x8400000000L&l)!=0L) jjCheckNAdd(18);
                        break;
                        case 22:
                        if ((0xffffff7fffffdbffL&l)!=0L) jjstateSet[jjnewStateCnt++]=18;
                        break;
                        case 23:
                        if (curChar==34) jjCheckNAddStates(7,9);
                        break;
                        case 25:
                        if ((0xff000000000000L&l)!=0L) jjCheckNAddStates(22,25);
                        break;
                        case 26:
                        if ((0xff000000000000L&l)!=0L) jjCheckNAddStates(7,9);
                        break;
                        case 27:
                        if ((0xfffffffbffffdbffL&l)!=0L) jjCheckNAddStates(7,9);
                        break;
                        case 28:
                        if (curChar==34&&kind>72) kind=72;
                        break;
                        case 29:
                        if ((0xf000000000000L&l)!=0L) jjstateSet[jjnewStateCnt++]=30;
                        break;
                        case 30:
                        if ((0xff000000000000L&l)!=0L) jjstateSet[jjnewStateCnt++]=26;
                        break;
                        case 31:
                        if ((0x8400000000L&l)!=0L) jjCheckNAddStates(7,9);
                        break;
                        case 32:
                        if (curChar!=36) break;
                        if (kind>121) kind=121;
                        jjCheckNAdd(33);
                        break;
                        case 33:
                        if ((0x3ff00100fffc1ffL&l)==0L) break;
                        if (kind>121) kind=121;
                        jjCheckNAdd(33);
                        break;
                        case 34:
                        if ((0x3ff000000000000L&l)!=0L) jjCheckNAddStates(0,6);
                        break;
                        case 35:
                        if ((0x3ff000000000000L&l)!=0L) jjCheckNAddTwoStates(35,36);
                        break;
                        case 36:
                        if (curChar!=46) break;
                        if (kind>66) kind=66;
                        jjAddStates(26,28);
                        break;
                        case 37:
                        if ((0x3ff000000000000L&l)==0L) break;
                        if (kind>66) kind=66;
                        jjCheckNAddStates(26,28);
                        break;
                        case 39:
                        if ((0x280000000000L&l)!=0L) jjstateSet[jjnewStateCnt++]=40;
                        break;
                        case 40:
                        if ((0x3ff000000000000L&l)==0L) break;
                        if (kind>66) kind=66;
                        jjCheckNAddTwoStates(40,13);
                        break;
                        case 41:
                        if ((0x3ff000000000000L&l)!=0L) jjCheckNAddTwoStates(41,42);
                        break;
                        case 43:
                        if ((0x280000000000L&l)!=0L) jjstateSet[jjnewStateCnt++]=44;
                        break;
                        case 44:
                        if ((0x3ff000000000000L&l)==0L) break;
                        if (kind>66) kind=66;
                        jjCheckNAddTwoStates(44,13);
                        break;
                        case 45:
                        if ((0x3ff000000000000L&l)!=0L) jjCheckNAddStates(29,31);
                        break;
                        case 47:
                        if ((0x280000000000L&l)!=0L) jjstateSet[jjnewStateCnt++]=48;
                        break;
                        case 48:
                        if ((0x3ff000000000000L&l)!=0L) jjCheckNAddTwoStates(48,13);
                        break;
                        case 49:
                        if (curChar!=48) break;
                        if (kind>62) kind=62;
                        jjCheckNAddStates(14,18);
                        break;
                        case 51:
                        if ((0x3ff000000000000L&l)==0L) break;
                        if (kind>62) kind=62;
                        jjCheckNAddTwoStates(51,7);
                        break;
                        case 52:
                        if ((0xff000000000000L&l)==0L) break;
                        if (kind>62) kind=62;
                        jjCheckNAddTwoStates(52,7);
                        break;
                        case 54:
                        if ((0x3ff000000000000L&l)!=0L) jjCheckNAddStates(32,34);
                        break;
                        case 55:
                        if (curChar==46) jjstateSet[jjnewStateCnt++]=56;
                        break;
                        case 57:
                        if ((0x280000000000L&l)!=0L) jjstateSet[jjnewStateCnt++]=58;
                        break;
                        case 58:
                        if ((0x3ff000000000000L&l)==0L) break;
                        if (kind>66) kind=66;
                        jjCheckNAddTwoStates(58,13);
                        break;
                        case 60:
                        if ((0x3ff000000000000L&l)!=0L) jjCheckNAddTwoStates(60,61);
                        break;
                        case 61:
                        if (curChar==46) jjstateSet[jjnewStateCnt++]=62;
                        break;
                        case 62:
                        if ((0x3ff000000000000L&l)!=0L) jjCheckNAddTwoStates(62,63);
                        break;
                        case 64:
                        if ((0x280000000000L&l)!=0L) jjstateSet[jjnewStateCnt++]=65;
                        break;
                        case 65:
                        if ((0x3ff000000000000L&l)==0L) break;
                        if (kind>66) kind=66;
                        jjCheckNAddTwoStates(65,13);
                        break;
                        default:
                        break;
                    }
                }
                while (i!=startsAt);
            }
            else if (curChar<128) {
                long l=1L<<(curChar&077);
                do {
                    switch(jjstateSet[--i]) {
                        case 4:
                        if ((0x7fffffe87fffffeL&l)==0L) break;
                        if (kind>121) kind=121;
                        jjCheckNAdd(33);
                        break;
                        case 2:
                        if (kind>3) kind=3;
                        break;
                        case 7:
                        if ((0x100000001000L&l)!=0L&&kind>62) kind=62;
                        break;
                        case 10:
                        if ((0x2000000020L&l)!=0L) jjAddStates(35,36);
                        break;
                        case 13:
                        if ((0x5000000050L&l)!=0L&&kind>66) kind=66;
                        break;
                        case 15:
                        if (curChar==92) jjAddStates(37,39);
                        break;
                        case 21:
                        if ((0x14404410000000L&l)!=0L) jjCheckNAdd(18);
                        break;
                        case 22:
                        if ((0xffffffffefffffffL&l)!=0L) jjstateSet[jjnewStateCnt++]=18;
                        break;
                        case 24:
                        if (curChar==92) jjAddStates(40,42);
                        break;
                        case 27:
                        if ((0xffffffffefffffffL&l)!=0L) jjCheckNAddStates(7,9);
                        break;
                        case 31:
                        if ((0x14404410000000L&l)!=0L) jjCheckNAddStates(7,9);
                        break;
                        case 33:
                        if ((0x87fffffe87fffffeL&l)==0L) break;
                        if (kind>121) kind=121;
                        jjCheckNAdd(33);
                        break;
                        case 38:
                        if ((0x2000000020L&l)!=0L) jjAddStates(43,44);
                        break;
                        case 42:
                        if ((0x2000000020L&l)!=0L) jjAddStates(45,46);
                        break;
                        case 46:
                        if ((0x2000000020L&l)!=0L) jjAddStates(47,48);
                        break;
                        case 50:
                        if ((0x100000001000000L&l)!=0L) jjstateSet[jjnewStateCnt++]=51;
                        break;
                        case 51:
                        if ((0x7e0000007eL&l)==0L) break;
                        if (kind>62) kind=62;
                        jjCheckNAddTwoStates(51,7);
                        break;
                        case 53:
                        if ((0x100000001000000L&l)!=0L) jjstateSet[jjnewStateCnt++]=54;
                        break;
                        case 54:
                        if ((0x7e0000007eL&l)!=0L) jjCheckNAddStates(32,34);
                        break;
                        case 56:
                        if ((0x1000000010000L&l)!=0L) jjAddStates(49,50);
                        break;
                        case 59:
                        if ((0x100000001000000L&l)!=0L) jjAddStates(51,52);
                        break;
                        case 60:
                        if ((0x7e0000007eL&l)!=0L) jjCheckNAddTwoStates(60,61);
                        break;
                        case 62:
                        if ((0x7e0000007eL&l)!=0L) jjCheckNAddTwoStates(62,63);
                        break;
                        case 63:
                        if ((0x1000000010000L&l)!=0L) jjAddStates(53,54);
                        break;
                        default:
                        break;
                    }
                }
                while (i!=startsAt);
            }
            else {
                int hiByte=(int)(curChar>>8);
                int i1=hiByte>>6;
                long l1=1L<<(hiByte&077);
                int i2=(curChar&0xff)>>6;
                long l2=1L<<(curChar&077);
                do {
                    switch(jjstateSet[--i]) {
                        case 4:
                        if (!jjCanMove_1(hiByte,i1,i2,l1,l2)) break;
                        if (kind>121) kind=121;
                        jjCheckNAdd(33);
                        break;
                        case 2:
                        if (jjCanMove_0(hiByte,i1,i2,l1,l2)&&kind>3) kind=3;
                        break;
                        case 22:
                        if (jjCanMove_0(hiByte,i1,i2,l1,l2)) jjstateSet[jjnewStateCnt++]=18;
                        break;
                        case 27:
                        if (jjCanMove_0(hiByte,i1,i2,l1,l2)) jjCheckNAddStates(7,9);
                        break;
                        case 33:
                        if (!jjCanMove_2(hiByte,i1,i2,l1,l2)) break;
                        if (kind>121) kind=121;
                        jjCheckNAdd(33);
                        break;
                        default:
                        break;
                    }
                }
                while (i!=startsAt);
            }
            if (kind!=0x7fffffff) {
                jjmatchedKind=kind;
                jjmatchedPos=curPos;
                kind=0x7fffffff;
            }
            ++curPos;
            if ((i=jjnewStateCnt)==(startsAt=66-(jjnewStateCnt=startsAt))) return curPos;
            try {
                curChar=input_stream.readChar();
            }
            catch(java.io.IOException e) {
                return curPos;
            }
        }
    }

    private int jjStartNfaWithStates_IN_SINGLE_LINE_COMMENT(int pos,int kind,int state) {
        jjmatchedKind=kind;
        jjmatchedPos=pos;
        try {
            curChar=input_stream.readChar();
        }
        catch(java.io.IOException e) {
            return pos+1;
        }
        return jjMoveNfa_IN_SINGLE_LINE_COMMENT(state,pos+1);
    }

    private int jjMoveStringLiteralDfa0_IN_SINGLE_LINE_COMMENT() {
        return jjMoveNfa_IN_SINGLE_LINE_COMMENT(1,0);
    }

    private int jjMoveNfa_IN_SINGLE_LINE_COMMENT(int startState,int curPos) {
        int startsAt=0;
        jjnewStateCnt=4;
        int i=1;
        jjstateSet[0]=startState;
        int kind=0x7fffffff;
        while (true) {
            if (++jjround==0x7fffffff) {
                ReInitRounds();
            }
            if (curChar<64) {
                long l=1L<<curChar;
                do {
                    switch(jjstateSet[--i]) {
                        case 1:
                         {
                            if (kind>8) kind=8;
                        }
                        if ((0x2400L&l)!=0L) {
                            if (kind>5) kind=5;
                        }
                        if (curChar==13) jjstateSet[jjnewStateCnt++]=0;
                        break;
                        case 0:
                        if (curChar==10&&kind>5) kind=5;
                        break;
                        case 2:
                        if ((0x2400L&l)!=0L&&kind>5) kind=5;
                        break;
                        case 3:
                        if (kind>8) kind=8;
                        break;
                        default:
                        break;
                    }
                }
                while (i!=startsAt);
            }
            else if (curChar<128) {
                long l=1L<<(curChar&077);
                do {
                    switch(jjstateSet[--i]) {
                        case 1:
                        kind=8;
                        break;
                        default:
                        break;
                    }
                }
                while (i!=startsAt);
            }
            else {
                int hiByte=(int)(curChar>>8);
                int i1=hiByte>>6;
                long l1=1L<<(hiByte&077);
                int i2=(curChar&0xff)>>6;
                long l2=1L<<(curChar&077);
                do {
                    switch(jjstateSet[--i]) {
                        case 1:
                        if (jjCanMove_0(hiByte,i1,i2,l1,l2)&&kind>8) kind=8;
                        break;
                        default:
                        break;
                    }
                }
                while (i!=startsAt);
            }
            if (kind!=0x7fffffff) {
                jjmatchedKind=kind;
                jjmatchedPos=curPos;
                kind=0x7fffffff;
            }
            ++curPos;
            if ((i=jjnewStateCnt)==(startsAt=4-(jjnewStateCnt=startsAt))) return curPos;
            try {
                curChar=input_stream.readChar();
            }
            catch(java.io.IOException e) {
                return curPos;
            }
        }
    }

    private int jjStartNfa_IN_FORMAL_COMMENT(int pos,long active0) {
        return jjMoveNfa_IN_FORMAL_COMMENT(jjStopStringLiteralDfa_IN_FORMAL_COMMENT(pos,active0),pos+1);
    }

    private final int jjStopStringLiteralDfa_IN_FORMAL_COMMENT(int pos,long active0) {
        switch(pos) {
            case 0:
            if ((active0&0x40L)!=0L) {
                jjmatchedKind=8;
                return-1;
            }
            return-1;
            case 1:
            if ((active0&0x40L)!=0L) {
                if (jjmatchedPos==0) {
                    jjmatchedKind=8;
                    jjmatchedPos=0;
                }
                return-1;
            }
            return-1;
            default:
            return-1;
        }
    }

    private int jjStartNfaWithStates_IN_FORMAL_COMMENT(int pos,int kind,int state) {
        jjmatchedKind=kind;
        jjmatchedPos=pos;
        try {
            curChar=input_stream.readChar();
        }
        catch(java.io.IOException e) {
            return pos+1;
        }
        return jjMoveNfa_IN_FORMAL_COMMENT(state,pos+1);
    }

    private int jjMoveStringLiteralDfa0_IN_FORMAL_COMMENT() {
        switch(curChar) {
            case 42:
            return jjMoveStringLiteralDfa1_IN_FORMAL_COMMENT(0x40L);
            default:
            return jjMoveNfa_IN_FORMAL_COMMENT(0,0);
        }
    }

    private int jjMoveStringLiteralDfa1_IN_FORMAL_COMMENT(long active0) {
        try {
            curChar=input_stream.readChar();
        }
        catch(java.io.IOException e) {
            jjStopStringLiteralDfa_IN_FORMAL_COMMENT(0,active0);
            return 1;
        }
        switch(curChar) {
            case 47:
            if ((active0&0x40L)!=0L) return jjStopAtPos(1,6);
            break;
            default:
            break;
        }
        return jjStartNfa_IN_FORMAL_COMMENT(0,active0);
    }

    private int jjMoveNfa_IN_FORMAL_COMMENT(int startState,int curPos) {
        int startsAt=0;
        jjnewStateCnt=1;
        int i=1;
        jjstateSet[0]=startState;
        int kind=0x7fffffff;
        while (true) {
            if (++jjround==0x7fffffff) {
                ReInitRounds();
            }
            if (curChar<64) {
                long l=1L<<curChar;
                do {
                    switch(jjstateSet[--i]) {
                        case 0:
                        kind=8;
                        break;
                        default:
                        break;
                    }
                }
                while (i!=startsAt);
            }
            else if (curChar<128) {
                long l=1L<<(curChar&077);
                do {
                    switch(jjstateSet[--i]) {
                        case 0:
                        kind=8;
                        break;
                        default:
                        break;
                    }
                }
                while (i!=startsAt);
            }
            else {
                int hiByte=(int)(curChar>>8);
                int i1=hiByte>>6;
                long l1=1L<<(hiByte&077);
                int i2=(curChar&0xff)>>6;
                long l2=1L<<(curChar&077);
                do {
                    switch(jjstateSet[--i]) {
                        case 0:
                        if (jjCanMove_0(hiByte,i1,i2,l1,l2)&&kind>8) kind=8;
                        break;
                        default:
                        break;
                    }
                }
                while (i!=startsAt);
            }
            if (kind!=0x7fffffff) {
                jjmatchedKind=kind;
                jjmatchedPos=curPos;
                kind=0x7fffffff;
            }
            ++curPos;
            if ((i=jjnewStateCnt)==(startsAt=1-(jjnewStateCnt=startsAt))) return curPos;
            try {
                curChar=input_stream.readChar();
            }
            catch(java.io.IOException e) {
                return curPos;
            }
        }
    }

    private int jjStartNfa_IN_MULTI_LINE_COMMENT(int pos,long active0) {
        return jjMoveNfa_IN_MULTI_LINE_COMMENT(jjStopStringLiteralDfa_IN_MULTI_LINE_COMMENT(pos,active0),pos+1);
    }

    private final int jjStopStringLiteralDfa_IN_MULTI_LINE_COMMENT(int pos,long active0) {
        switch(pos) {
            case 0:
            if ((active0&0x80L)!=0L) {
                jjmatchedKind=8;
                return-1;
            }
            return-1;
            case 1:
            if ((active0&0x80L)!=0L) {
                if (jjmatchedPos==0) {
                    jjmatchedKind=8;
                    jjmatchedPos=0;
                }
                return-1;
            }
            return-1;
            default:
            return-1;
        }
    }

    private int jjStartNfaWithStates_IN_MULTI_LINE_COMMENT(int pos,int kind,int state) {
        jjmatchedKind=kind;
        jjmatchedPos=pos;
        try {
            curChar=input_stream.readChar();
        }
        catch(java.io.IOException e) {
            return pos+1;
        }
        return jjMoveNfa_IN_MULTI_LINE_COMMENT(state,pos+1);
    }

    private int jjMoveStringLiteralDfa0_IN_MULTI_LINE_COMMENT() {
        switch(curChar) {
            case 42:
            return jjMoveStringLiteralDfa1_IN_MULTI_LINE_COMMENT(0x80L);
            default:
            return jjMoveNfa_IN_MULTI_LINE_COMMENT(0,0);
        }
    }

    private int jjMoveStringLiteralDfa1_IN_MULTI_LINE_COMMENT(long active0) {
        try {
            curChar=input_stream.readChar();
        }
        catch(java.io.IOException e) {
            jjStopStringLiteralDfa_IN_MULTI_LINE_COMMENT(0,active0);
            return 1;
        }
        switch(curChar) {
            case 47:
            if ((active0&0x80L)!=0L) return jjStopAtPos(1,7);
            break;
            default:
            break;
        }
        return jjStartNfa_IN_MULTI_LINE_COMMENT(0,active0);
    }

    private int jjMoveNfa_IN_MULTI_LINE_COMMENT(int startState,int curPos) {
        int startsAt=0;
        jjnewStateCnt=1;
        int i=1;
        jjstateSet[0]=startState;
        int kind=0x7fffffff;
        while (true) {
            if (++jjround==0x7fffffff) {
                ReInitRounds();
            }
            if (curChar<64) {
                long l=1L<<curChar;
                do {
                    switch(jjstateSet[--i]) {
                        case 0:
                        kind=8;
                        break;
                        default:
                        break;
                    }
                }
                while (i!=startsAt);
            }
            else if (curChar<128) {
                long l=1L<<(curChar&077);
                do {
                    switch(jjstateSet[--i]) {
                        case 0:
                        kind=8;
                        break;
                        default:
                        break;
                    }
                }
                while (i!=startsAt);
            }
            else {
                int hiByte=(int)(curChar>>8);
                int i1=hiByte>>6;
                long l1=1L<<(hiByte&077);
                int i2=(curChar&0xff)>>6;
                long l2=1L<<(curChar&077);
                do {
                    switch(jjstateSet[--i]) {
                        case 0:
                        if (jjCanMove_0(hiByte,i1,i2,l1,l2)&&kind>8) kind=8;
                        break;
                        default:
                        break;
                    }
                }
                while (i!=startsAt);
            }
            if (kind!=0x7fffffff) {
                jjmatchedKind=kind;
                jjmatchedPos=curPos;
                kind=0x7fffffff;
            }
            ++curPos;
            if ((i=jjnewStateCnt)==(startsAt=1-(jjnewStateCnt=startsAt))) return curPos;
            try {
                curChar=input_stream.readChar();
            }
            catch(java.io.IOException e) {
                return curPos;
            }
        }
    }

    static final int[] jjnextStates={35,36,41,42,45,46,13,24,27,28,15,22,6,7,50,52,7,53,59,9,10,13,24,26,27,28,37,38,13,45,46,13,54,55,56,11,12,16,19,21,25,29,31,39,40,43,44,47,48,57,58,60,61,64,65};
}
