/* Generated by: FreeCC 0.9.3. Do not edit. JavaDocComment.java */
package org.owasp.orizon.mirage.java.parser;

public class JavaDocComment extends Comment {
    public JavaDocComment(int kind,String image) {
        super(kind,image);
    }

}
