/* Generated by: FreeCC 0.9.3. Do not edit. KeyWord.java */
package org.owasp.orizon.mirage.java.parser;

public class KeyWord extends Token {
    public KeyWord(int kind,String image) {
        super(kind,image);
    }

}
