/* Generated by: FreeCC 0.9.3. Do not edit. LabeledStatement.java */
package org.owasp.orizon.mirage.java.parser;

public class LabeledStatement extends BaseNode {
    public LabeledStatement(int id) {
        super(id);
    }

    public LabeledStatement() {
        super(JavaConstants.LABELEDSTATEMENT);
    }

}
