/* Generated by: FreeCC 0.9.3. Do not edit. Literal.java */
package org.owasp.orizon.mirage.java.parser;

public class Literal extends Token {
    public Literal(int kind,String image) {
        super(kind,image);
    }

}
