/* Generated by: FreeCC 0.9.3. Do not edit. LocalVariableDeclaration.java */
package org.owasp.orizon.mirage.java.parser;

public class LocalVariableDeclaration extends BaseNode {
    public LocalVariableDeclaration(int id) {
        super(id);
    }

    public LocalVariableDeclaration() {
        super(JavaConstants.LOCALVARIABLEDECLARATION);
    }

}
