/* Generated by: FreeCC 0.9.3. Do not edit. MemberValuePair.java */
package org.owasp.orizon.mirage.java.parser;

public class MemberValuePair extends BaseNode {
    public MemberValuePair(int id) {
        super(id);
    }

    public MemberValuePair() {
        super(JavaConstants.MEMBERVALUEPAIR);
    }

}
