/* Generated by: FreeCC 0.9.3. Do not edit. MemberValuePairs.java */
package org.owasp.orizon.mirage.java.parser;

public class MemberValuePairs extends BaseNode {
    public MemberValuePairs(int id) {
        super(id);
    }

    public MemberValuePairs() {
        super(JavaConstants.MEMBERVALUEPAIRS);
    }

}
