/* Generated by: FreeCC 0.9.3. Do not edit. MemberValue.java */
package org.owasp.orizon.mirage.java.parser;

public class MemberValue extends BaseNode {
    public MemberValue(int id) {
        super(id);
    }

    public MemberValue() {
        super(JavaConstants.MEMBERVALUE);
    }

}
