/* Generated by: FreeCC 0.9.3. Do not edit. MemberValueArrayInitializer.java */
package org.owasp.orizon.mirage.java.parser;

public class MemberValueArrayInitializer extends BaseNode {
    public MemberValueArrayInitializer(int id) {
        super(id);
    }

    public MemberValueArrayInitializer() {
        super(JavaConstants.MEMBERVALUEARRAYINITIALIZER);
    }

}
