/* Generated by: FreeCC 0.9.3. Do not edit. MemberSelector.java */
package org.owasp.orizon.mirage.java.parser;

public class MemberSelector extends BaseNode {
    public MemberSelector(int id) {
        super(id);
    }

    public MemberSelector() {
        super(JavaConstants.MEMBERSELECTOR);
    }

}
