/* Generated by: FreeCC 0.9.3. Do not edit. MethodDeclaration.java */
package org.owasp.orizon.mirage.java.parser;

public class MethodDeclaration extends BaseNode {
    public String getName() {
        for(Node n : children) {
            if (n.getId()==IDENTIFIER) {
                return n.toString();
            }
        }
        throw new IllegalStateException();
    }

    public FormalParams getFormalParams() {
        return Nodes.firstChildOfType(this,FormalParams.class);
    }

    public String getFullSignature() {
        return getName()+getFormalParams();
    }

    public MethodDeclaration(int id) {
        super(id);
    }

    public MethodDeclaration() {
        super(JavaConstants.METHODDECLARATION);
    }

}
