/* Generated by: FreeCC 0.9.3. Do not edit. Modifiers.java */
package org.owasp.orizon.mirage.java.parser;

public class Modifiers extends BaseNode {
    public Modifiers(int id) {
        super(id);
    }

    public Modifiers() {
        super(JavaConstants.MODIFIERS);
    }

}
