/* Generated by: FreeCC 0.9.3. Do not edit. MultiplicativeExpression.java */
package org.owasp.orizon.mirage.java.parser;

public class MultiplicativeExpression extends Expression {
    public MultiplicativeExpression(int id) {
        super(id);
    }

    public MultiplicativeExpression() {
        super(JavaConstants.MULTIPLICATIVEEXPRESSION);
    }

}
