/* Generated by: FreeCC 0.9.3. Do not edit. ObjectType.java */
package org.owasp.orizon.mirage.java.parser;

public class ObjectType extends BaseNode {
    public boolean equals(Object obj) {
        if (obj instanceof ObjectType) {
            return((ObjectType) obj).toString().equals(this.toString());
        }
        return false;
    }

    public String toString() {
        StringBuilder buf=new StringBuilder();
        for(Token t : Nodes.getRealTokens(this)) {
            buf.append(t);
        }
        return buf.toString();
    }

    public ObjectType(int id) {
        super(id);
    }

    public ObjectType() {
        super(JavaConstants.OBJECTTYPE);
    }

}
