/* Generated by: FreeCC 0.9.3. Do not edit. Operator.java */
package org.owasp.orizon.mirage.java.parser;

public class Operator extends Token {
    public Operator(int kind,String image) {
        super(kind,image);
    }

}
