/* Generated by: FreeCC 0.9.3. Do not edit. PackageDeclaration.java */
package org.owasp.orizon.mirage.java.parser;

public class PackageDeclaration extends BaseNode {
    public String getPackageName() {
        StringBuilder buf=new StringBuilder();
        boolean seenPackage=false;
        for(Token t : Nodes.getRealTokens(this)) {
            if (t.getId()==PACKAGE) {
                seenPackage=true;
            }
            else if (seenPackage) {
                if (t.getId()!=SEMICOLON) buf.append(t);
            }
        }
        return buf.toString();
    }

    public PackageDeclaration(int id) {
        super(id);
    }

    public PackageDeclaration() {
        super(JavaConstants.PACKAGEDECLARATION);
    }

}
