/* Generated by: FreeCC 0.9.3. Do not edit. PostfixExpression.java */
package org.owasp.orizon.mirage.java.parser;

public class PostfixExpression extends Expression {
    public PostfixExpression(int id) {
        super(id);
    }

    public PostfixExpression() {
        super(JavaConstants.POSTFIXEXPRESSION);
    }

}
