/* Generated by: FreeCC 0.9.3. Do not edit. PreDecrementExpression.java */
package org.owasp.orizon.mirage.java.parser;

public class PreDecrementExpression extends Expression {
    public PreDecrementExpression(int id) {
        super(id);
    }

    public PreDecrementExpression() {
        super(JavaConstants.PREDECREMENTEXPRESSION);
    }

}
