/* Generated by: FreeCC 0.9.3. Do not edit. PreIncrementExpression.java */
package org.owasp.orizon.mirage.java.parser;

public class PreIncrementExpression extends Expression {
    public PreIncrementExpression(int id) {
        super(id);
    }

    public PreIncrementExpression() {
        super(JavaConstants.PREINCREMENTEXPRESSION);
    }

}
