/* Generated by: FreeCC 0.9.3. Do not edit. PrimitiveArrayType.java */
package org.owasp.orizon.mirage.java.parser;

public class PrimitiveArrayType extends BaseNode {
    public PrimitiveArrayType(int id) {
        super(id);
    }

    public PrimitiveArrayType() {
        super(JavaConstants.PRIMITIVEARRAYTYPE);
    }

}
