/* Generated by: FreeCC 0.9.3. Do not edit. PrimarySuffix.java */
package org.owasp.orizon.mirage.java.parser;

public class PrimarySuffix extends BaseNode {
    public PrimarySuffix(int id) {
        super(id);
    }

    public PrimarySuffix() {
        super(JavaConstants.PRIMARYSUFFIX);
    }

}
