/* Generated by: FreeCC 0.9.3. Do not edit. PrimaryPrefix.java */
package org.owasp.orizon.mirage.java.parser;

public class PrimaryPrefix extends BaseNode {
    public PrimaryPrefix(int id) {
        super(id);
    }

    public PrimaryPrefix() {
        super(JavaConstants.PRIMARYPREFIX);
    }

}
