/* Generated by: FreeCC 0.9.3. Do not edit. PUBLIC.java */
package org.owasp.orizon.mirage.java.parser;

public class PUBLIC extends Token {
    public PUBLIC(int kind,String image) {
        super(kind,image);
    }

}
