/* Generated by: FreeCC 0.9.3. Do not edit. ReferenceType.java */
package org.owasp.orizon.mirage.java.parser;

public class ReferenceType extends BaseNode {
    public ReferenceType(int id) {
        super(id);
    }

    public ReferenceType() {
        super(JavaConstants.REFERENCETYPE);
    }

}
