/* Generated by: FreeCC 0.9.3. Do not edit. RelationalExpression.java */
package org.owasp.orizon.mirage.java.parser;

public class RelationalExpression extends Expression {
    public RelationalExpression(int id) {
        super(id);
    }

    public RelationalExpression() {
        super(JavaConstants.RELATIONALEXPRESSION);
    }

}
