/* Generated by: FreeCC 0.9.3. Do not edit. ReturnStatement.java */
package org.owasp.orizon.mirage.java.parser;

public class ReturnStatement extends BaseNode {
    public ReturnStatement(int id) {
        super(id);
    }

    public ReturnStatement() {
        super(JavaConstants.RETURNSTATEMENT);
    }

}
