/* Generated by: FreeCC 0.9.3. Do not edit. ReturnType.java */
package org.owasp.orizon.mirage.java.parser;

public class ReturnType extends BaseNode {
    public ReturnType(int id) {
        super(id);
    }

    public ReturnType() {
        super(JavaConstants.RETURNTYPE);
    }

}
