/* Generated by: FreeCC 0.9.3. Do not edit. ShiftExpression.java */
package org.owasp.orizon.mirage.java.parser;

public class ShiftExpression extends Expression {
    public ShiftExpression(int id) {
        super(id);
    }

    public ShiftExpression() {
        super(JavaConstants.SHIFTEXPRESSION);
    }

}
