/* Generated by: FreeCC 0.9.3. Do not edit. StatementExpressionList.java */
package org.owasp.orizon.mirage.java.parser;

public class StatementExpressionList extends BaseNode {
    public StatementExpressionList(int id) {
        super(id);
    }

    public StatementExpressionList() {
        super(JavaConstants.STATEMENTEXPRESSIONLIST);
    }

}
