/* Generated by: FreeCC 0.9.3. Do not edit. StatementExpression.java */
package org.owasp.orizon.mirage.java.parser;

public class StatementExpression extends BaseNode {
    public StatementExpression(int id) {
        super(id);
    }

    public StatementExpression() {
        super(JavaConstants.STATEMENTEXPRESSION);
    }

}
