/* Generated by: FreeCC 0.9.3. Do not edit. SwitchLabel.java */
package org.owasp.orizon.mirage.java.parser;

public class SwitchLabel extends BaseNode {
    public SwitchLabel(int id) {
        super(id);
    }

    public SwitchLabel() {
        super(JavaConstants.SWITCHLABEL);
    }

}
