/* Generated by: FreeCC 0.9.3. Do not edit. SwitchStatement.java */
package org.owasp.orizon.mirage.java.parser;

public class SwitchStatement extends BaseNode {
    public SwitchStatement(int id) {
        super(id);
    }

    public SwitchStatement() {
        super(JavaConstants.SWITCHSTATEMENT);
    }

}
