/* Generated by: FreeCC 0.9.3. Do not edit. SynchronizedStatement.java */
package org.owasp.orizon.mirage.java.parser;

public class SynchronizedStatement extends BaseNode {
    public SynchronizedStatement(int id) {
        super(id);
    }

    public SynchronizedStatement() {
        super(JavaConstants.SYNCHRONIZEDSTATEMENT);
    }

}
