/* Generated by: FreeCC 0.9.3. Do not edit. TernaryExpression.java */
package org.owasp.orizon.mirage.java.parser;

public class TernaryExpression extends Expression {
    public TernaryExpression(int id) {
        super(id);
    }

    public TernaryExpression() {
        super(JavaConstants.TERNARYEXPRESSION);
    }

}
