/* Generated by: FreeCC 0.9.3. Do not edit. ThrowsList.java */
package org.owasp.orizon.mirage.java.parser;

import java.util.List;
public class ThrowsList extends BaseNode {
    public List<Name>getTypes() {
        return Nodes.childrenOfType(this,Name.class);
    }

    public ThrowsList(int id) {
        super(id);
    }

    public ThrowsList() {
        super(JavaConstants.THROWSLIST);
    }

}
