/* Generated by: FreeCC 0.9.3. Do not edit. ThrowStatement.java */
package org.owasp.orizon.mirage.java.parser;

public class ThrowStatement extends BaseNode {
    public ThrowStatement(int id) {
        super(id);
    }

    public ThrowStatement() {
        super(JavaConstants.THROWSTATEMENT);
    }

}
