/* Generated by: FreeCC 0.9.3. Do not edit. TryStatement.java */
package org.owasp.orizon.mirage.java.parser;

public class TryStatement extends BaseNode {
    public TryStatement(int id) {
        super(id);
    }

    public TryStatement() {
        super(JavaConstants.TRYSTATEMENT);
    }

}
