/* Generated by: FreeCC 0.9.3. Do not edit. Type.java */
package org.owasp.orizon.mirage.java.parser;

public class Type extends BaseNode {
    public Type(int id) {
        super(id);
    }

    public Type() {
        super(JavaConstants.TYPE);
    }

}
