/* Generated by: FreeCC 0.9.3. Do not edit. TypeArguments.java */
package org.owasp.orizon.mirage.java.parser;

public class TypeArguments extends BaseNode {
    public TypeArguments(int id) {
        super(id);
    }

    public TypeArguments() {
        super(JavaConstants.TYPEARGUMENTS);
    }

}
