/* Generated by: FreeCC 0.9.3. Do not edit. TypeBound.java */
package org.owasp.orizon.mirage.java.parser;

public class TypeBound extends BaseNode {
    public TypeBound(int id) {
        super(id);
    }

    public TypeBound() {
        super(JavaConstants.TYPEBOUND);
    }

}
