/* Generated by: FreeCC 0.9.3. Do not edit. TypeParameter.java */
package org.owasp.orizon.mirage.java.parser;

public class TypeParameter extends BaseNode {
    public TypeParameter(int id) {
        super(id);
    }

    public TypeParameter() {
        super(JavaConstants.TYPEPARAMETER);
    }

}
