/* Generated by: FreeCC 0.9.3. Do not edit. TypeArgument.java */
package org.owasp.orizon.mirage.java.parser;

public class TypeArgument extends BaseNode {
    public TypeArgument(int id) {
        super(id);
    }

    public TypeArgument() {
        super(JavaConstants.TYPEARGUMENT);
    }

}
