/* Generated by: FreeCC 0.9.3. Do not edit. TypeParameterList.java */
package org.owasp.orizon.mirage.java.parser;

import java.util.*;
public class TypeParameterList extends BaseNode {
    public void add(TypeParameter param) {
        if (!getParameters().contains(param)) {
            ListIterator<Node>iterator=iterator();
            while (iterator.hasNext()) {
                iterator.next();
            }
            iterator.previous();
            iterator.add(Token.newToken(COMMA,","));
            iterator.next();
            iterator.add(param);
        }
    }

    public void add(TypeParameterList params) {
        for(TypeParameter param : params.getParameters()) {
            add(param);
        }
    }

    public List<TypeParameter>getParameters() {
        return Nodes.childrenOfType(this,TypeParameter.class);
    }

    public TypeParameterList(int id) {
        super(id);
    }

    public TypeParameterList() {
        super(JavaConstants.TYPEPARAMETERLIST);
    }

}
