/* Generated by: FreeCC 0.9.3. Do not edit. UnaryExpressionNotPlusMinus.java */
package org.owasp.orizon.mirage.java.parser;

public class UnaryExpressionNotPlusMinus extends Expression {
    public UnaryExpressionNotPlusMinus(int id) {
        super(id);
    }

    public UnaryExpressionNotPlusMinus() {
        super(JavaConstants.UNARYEXPRESSIONNOTPLUSMINUS);
    }

}
