/* Generated by: FreeCC 0.9.3. Do not edit. UnaryExpression.java */
package org.owasp.orizon.mirage.java.parser;

public class UnaryExpression extends Expression {
    public UnaryExpression(int id) {
        super(id);
    }

    public UnaryExpression() {
        super(JavaConstants.UNARYEXPRESSION);
    }

}
