/* Generated by: FreeCC 0.9.3. Do not edit. VariableInitializer.java */
package org.owasp.orizon.mirage.java.parser;

public class VariableInitializer extends BaseNode {
    public VariableInitializer(int id) {
        super(id);
    }

    public VariableInitializer() {
        super(JavaConstants.VARIABLEINITIALIZER);
    }

}
