/* Generated by: FreeCC 0.9.3. Do not edit. VariableDeclaratorId.java */
package org.owasp.orizon.mirage.java.parser;

public class VariableDeclaratorId extends BaseNode {
    public VariableDeclaratorId(int id) {
        super(id);
    }

    public VariableDeclaratorId() {
        super(JavaConstants.VARIABLEDECLARATORID);
    }

}
