/* Generated by: FreeCC 0.9.3. Do not edit. VariableDeclarator.java */
package org.owasp.orizon.mirage.java.parser;

public class VariableDeclarator extends BaseNode {
    public VariableDeclarator(int id) {
        super(id);
    }

    public VariableDeclarator() {
        super(JavaConstants.VARIABLEDECLARATOR);
    }

}
