/* Generated by: FreeCC 0.9.3. Do not edit. WhileStatement.java */
package org.owasp.orizon.mirage.java.parser;

public class WhileStatement extends BaseNode {
    public WhileStatement(int id) {
        super(id);
    }

    public WhileStatement() {
        super(JavaConstants.WHILESTATEMENT);
    }

}
