/* Generated by: FreeCC 0.9.3. Do not edit. Whitespace.java */
package org.owasp.orizon.mirage.java.parser;

public class Whitespace extends Token {
    public Whitespace(int kind,String image) {
        super(kind,image);
    }

}
