/* Generated by: FreeCC 0.9.3. Do not edit. WildcardBounds.java */
package org.owasp.orizon.mirage.java.parser;

public class WildcardBounds extends BaseNode {
    public WildcardBounds(int id) {
        super(id);
    }

    public WildcardBounds() {
        super(JavaConstants.WILDCARDBOUNDS);
    }

}
