/* Generated by: FreeCC 0.9.3. Do not edit. ATTR_NAME.java */
package org.owasp.orizon.mirage.jsp.parser;

public class ATTR_NAME extends Token {
    public ATTR_NAME(int kind,String image) {
        super(kind,image);
    }

}
