/* Generated by: FreeCC 0.9.3. Do not edit. AttributeValue.java */
package org.owasp.orizon.mirage.jsp.parser;

public class AttributeValue extends BaseNode {
    private String image;
    public String toString() {
        return super.toString()+" - "+getImage();
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image=image;
    }

    public AttributeValue(int id) {
        super(id);
    }

    public AttributeValue() {
        super(JspConstants.ATTRIBUTEVALUE);
    }

}
