/* Generated by: FreeCC 0.9.3. Do not edit. Attribute.java */
package org.owasp.orizon.mirage.jsp.parser;

public class Attribute extends BaseNode {
    private String name;
    public String toString() {
        return super.toString()+" - "+getName();
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name=name;
    }

    public Attribute(int id) {
        super(id);
    }

    public Attribute() {
        super(JspConstants.ATTRIBUTE);
    }

}
