/* Generated by: FreeCC 0.9.3. Do not edit. ATTR_EQ.java */
package org.owasp.orizon.mirage.jsp.parser;

public class ATTR_EQ extends Token {
    public ATTR_EQ(int kind,String image) {
        super(kind,image);
    }

}
