/* Generated by: FreeCC 0.9.3. Do not edit. CDATA_START.java */
package org.owasp.orizon.mirage.jsp.parser;

public class CDATA_START extends Token {
    public CDATA_START(int kind,String image) {
        super(kind,image);
    }

}
