/* Generated by: FreeCC 0.9.3. Do not edit. CData.java */
package org.owasp.orizon.mirage.jsp.parser;

public class CData extends BaseNode {
    private String image;
    public String toString() {
        return super.toString()+" - "+getImage();
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image=image;
    }

    public CData(int id) {
        super(id);
    }

    public CData() {
        super(JspConstants.CDATA);
    }

}
