/* Generated by: FreeCC 0.9.3. Do not edit. CDATA_END.java */
package org.owasp.orizon.mirage.jsp.parser;

public class CDATA_END extends Token {
    public CDATA_END(int kind,String image) {
        super(kind,image);
    }

}
