/* Generated by: FreeCC 0.9.3. Do not edit. COMMENT_END.java */
package org.owasp.orizon.mirage.jsp.parser;

public class COMMENT_END extends Token {
    public COMMENT_END(int kind,String image) {
        super(kind,image);
    }

}
