/* Generated by: FreeCC 0.9.3. Do not edit. COMMENT_TEXT.java */
package org.owasp.orizon.mirage.jsp.parser;

public class COMMENT_TEXT extends Token {
    public COMMENT_TEXT(int kind,String image) {
        super(kind,image);
    }

}
