/* Generated by: FreeCC 0.9.3. Do not edit. COMMENT_START.java */
package org.owasp.orizon.mirage.jsp.parser;

public class COMMENT_START extends Token {
    public COMMENT_START(int kind,String image) {
        super(kind,image);
    }

}
