/* Generated by: FreeCC 0.9.3. Do not edit. CompilationUnit.java */
package org.owasp.orizon.mirage.jsp.parser;

public class CompilationUnit extends BaseNode {
    public CompilationUnit(int id) {
        super(id);
    }

    public CompilationUnit() {
        super(JspConstants.COMPILATIONUNIT);
    }

}
