/* Generated by: FreeCC 0.9.3. Do not edit. Content.java */
package org.owasp.orizon.mirage.jsp.parser;

public class Content extends BaseNode {
    public Content(int id) {
        super(id);
    }

    public Content() {
        super(JspConstants.CONTENT);
    }

}
