/* Generated by: FreeCC 0.9.3. Do not edit. DECL_START.java */
package org.owasp.orizon.mirage.jsp.parser;

public class DECL_START extends Token {
    public DECL_START(int kind,String image) {
        super(kind,image);
    }

}
