/* Generated by: FreeCC 0.9.3. Do not edit. DECL_END.java */
package org.owasp.orizon.mirage.jsp.parser;

public class DECL_END extends Token {
    public DECL_END(int kind,String image) {
        super(kind,image);
    }

}
