/* Generated by: FreeCC 0.9.3. Do not edit. Declaration.java */
package org.owasp.orizon.mirage.jsp.parser;

public class Declaration extends BaseNode {
    private String name;
    public String toString() {
        return super.toString()+" - "+getName();
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name=name;
    }

    public Declaration(int id) {
        super(id);
    }

    public Declaration() {
        super(JspConstants.DECLARATION);
    }

}
