/* Generated by: FreeCC 0.9.3. Do not edit. DoctypeExternalId.java */
package org.owasp.orizon.mirage.jsp.parser;

public class DoctypeExternalId extends BaseNode {
    private String image;
    private String uri;
    private String publicId;
    public String toString() {
        return super.toString()+" - "+getImage();
    }

    public void setPublicId(String id) {
        this.publicId=id;
    }

    public String getPublicId() {
        return publicId;
    }

    public String geUri() {
        return uri;
    }

    public void setUri(String uri) {
        this.uri=uri;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image=image;
    }

    public DoctypeExternalId(int id) {
        super(id);
    }

    public DoctypeExternalId() {
        super(JspConstants.DOCTYPEEXTERNALID);
    }

}
