/* Generated by: FreeCC 0.9.3. Do not edit. DOCTYPE_DECL_END.java */
package org.owasp.orizon.mirage.jsp.parser;

public class DOCTYPE_DECL_END extends Token {
    public DOCTYPE_DECL_END(int kind,String image) {
        super(kind,image);
    }

}
