/* Generated by: FreeCC 0.9.3. Do not edit. DOCTYPE_DECL_START.java */
package org.owasp.orizon.mirage.jsp.parser;

public class DOCTYPE_DECL_START extends Token {
    public DOCTYPE_DECL_START(int kind,String image) {
        super(kind,image);
    }

}
