/* Generated by: FreeCC 0.9.3. Do not edit. DOLLAR_OR_HASH_SINGLE_QUOTE.java */
package org.owasp.orizon.mirage.jsp.parser;

public class DOLLAR_OR_HASH_SINGLE_QUOTE extends Token {
    public DOLLAR_OR_HASH_SINGLE_QUOTE(int kind,String image) {
        super(kind,image);
    }

}
