/* Generated by: FreeCC 0.9.3. Do not edit. DOUBLE_QUOTE.java */
package org.owasp.orizon.mirage.jsp.parser;

public class DOUBLE_QUOTE extends Token {
    public DOUBLE_QUOTE(int kind,String image) {
        super(kind,image);
    }

}
