/* Generated by: FreeCC 0.9.3. Do not edit. EL_EXPRESSION_IN_ATTRIBUTE.java */
package org.owasp.orizon.mirage.jsp.parser;

public class EL_EXPRESSION_IN_ATTRIBUTE extends Token {
    public EL_EXPRESSION_IN_ATTRIBUTE(int kind,String image) {
        super(kind,image);
    }

}
