/* Generated by: FreeCC 0.9.3. Do not edit. EL_EXPRESSION.java */
package org.owasp.orizon.mirage.jsp.parser;

public class EL_EXPRESSION extends Token {
    public EL_EXPRESSION(int kind,String image) {
        super(kind,image);
    }

}
