/* Generated by: FreeCC 0.9.3. Do not edit. Element.java */
package org.owasp.orizon.mirage.jsp.parser;

public class Element extends BaseNode {
    private String image;
    private boolean empty;
    private String name;
    public String toString() {
        return super.toString()+" - "+getImage();
    }

    public boolean getEmpty() {
        return empty;
    }

    public void setEmpty(boolean val) {
        this.empty=val;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image=image;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name=name;
    }

    public Element(int id) {
        super(id);
    }

    public Element() {
        super(JspConstants.ELEMENT);
    }

}
