/* Generated by: FreeCC 0.9.3. Do not edit. ElExpression.java */
package org.owasp.orizon.mirage.jsp.parser;

public class ElExpression extends BaseNode {
    private String image;
    public String toString() {
        return super.toString()+" - "+getImage();
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image=image;
    }

    public ElExpression(int id) {
        super(id);
    }

    public ElExpression() {
        super(JspConstants.ELEXPRESSION);
    }

}
