/* Generated by: FreeCC 0.9.3. Do not edit. ENDING_DOUBLE_QUOTE.java */
package org.owasp.orizon.mirage.jsp.parser;

public class ENDING_DOUBLE_QUOTE extends Token {
    public ENDING_DOUBLE_QUOTE(int kind,String image) {
        super(kind,image);
    }

}
