/* Generated by: FreeCC 0.9.3. Do not edit. ENDING_SINGLE_QUOTE.java */
package org.owasp.orizon.mirage.jsp.parser;

public class ENDING_SINGLE_QUOTE extends Token {
    public ENDING_SINGLE_QUOTE(int kind,String image) {
        super(kind,image);
    }

}
