/* Generated by: FreeCC 0.9.3. Do not edit. ENDTAG_START.java */
package org.owasp.orizon.mirage.jsp.parser;

public class ENDTAG_START extends Token {
    public ENDTAG_START(int kind,String image) {
        super(kind,image);
    }

}
