/* Generated by: FreeCC 0.9.3. Do not edit. IN_TAG_ERROR.java */
package org.owasp.orizon.mirage.jsp.parser;

public class IN_TAG_ERROR extends Token {
    public IN_TAG_ERROR(int kind,String image) {
        super(kind,image);
    }

}
