/* Generated by: FreeCC 0.9.3. Do not edit. JSP_COMMENT_CONTENT.java */
package org.owasp.orizon.mirage.jsp.parser;

public class JSP_COMMENT_CONTENT extends Token {
    public JSP_COMMENT_CONTENT(int kind,String image) {
        super(kind,image);
    }

}
