/* Generated by: FreeCC 0.9.3. Do not edit. JSP_EXPRESSION.java */
package org.owasp.orizon.mirage.jsp.parser;

public class JSP_EXPRESSION extends Token {
    public JSP_EXPRESSION(int kind,String image) {
        super(kind,image);
    }

}
