/* Generated by: FreeCC 0.9.3. Do not edit. JSP_DECLARATION_END.java */
package org.owasp.orizon.mirage.jsp.parser;

public class JSP_DECLARATION_END extends Token {
    public JSP_DECLARATION_END(int kind,String image) {
        super(kind,image);
    }

}
