/* Generated by: FreeCC 0.9.3. Do not edit. JSP_DIRECTIVE_START.java */
package org.owasp.orizon.mirage.jsp.parser;

public class JSP_DIRECTIVE_START extends Token {
    public JSP_DIRECTIVE_START(int kind,String image) {
        super(kind,image);
    }

}
