/* Generated by: FreeCC 0.9.3. Do not edit. JSP_EXPRESSION_IN_ATTRIBUTE.java */
package org.owasp.orizon.mirage.jsp.parser;

public class JSP_EXPRESSION_IN_ATTRIBUTE extends Token {
    public JSP_EXPRESSION_IN_ATTRIBUTE(int kind,String image) {
        super(kind,image);
    }

}
