/* Generated by: FreeCC 0.9.3. Do not edit. JSP_DIRECTIVE_ATTRIBUTE_EQUALS.java */
package org.owasp.orizon.mirage.jsp.parser;

public class JSP_DIRECTIVE_ATTRIBUTE_EQUALS extends Token {
    public JSP_DIRECTIVE_ATTRIBUTE_EQUALS(int kind,String image) {
        super(kind,image);
    }

}
