/* Generated by: FreeCC 0.9.3. Do not edit. JSP_SCRIPTLET.java */
package org.owasp.orizon.mirage.jsp.parser;

public class JSP_SCRIPTLET extends Token {
    public JSP_SCRIPTLET(int kind,String image) {
        super(kind,image);
    }

}
