/* Generated by: FreeCC 0.9.3. Do not edit. JSP_DIRECTIVE_END.java */
package org.owasp.orizon.mirage.jsp.parser;

public class JSP_DIRECTIVE_END extends Token {
    public JSP_DIRECTIVE_END(int kind,String image) {
        super(kind,image);
    }

}
