/* Generated by: FreeCC 0.9.3. Do not edit. JSP_DECLARATION.java */
package org.owasp.orizon.mirage.jsp.parser;

public class JSP_DECLARATION extends Token {
    public JSP_DECLARATION(int kind,String image) {
        super(kind,image);
    }

}
