/* Generated by: FreeCC 0.9.3. Do not edit. JspComment.java */
package org.owasp.orizon.mirage.jsp.parser;

public class JspComment extends BaseNode {
    private String image;
    public String toString() {
        return super.toString()+" - "+getImage();
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image=image;
    }

    public JspComment(int id) {
        super(id);
    }

    public JspComment() {
        super(JspConstants.JSPCOMMENT);
    }

}
