/* Generated by: FreeCC 0.9.3. Do not edit. JspDeclaration.java */
package org.owasp.orizon.mirage.jsp.parser;

public class JspDeclaration extends BaseNode {
    private String image;
    public String toString() {
        return super.toString()+" - "+getImage();
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image=image;
    }

    public JspDeclaration(int id) {
        super(id);
    }

    public JspDeclaration() {
        super(JspConstants.JSPDECLARATION);
    }

}
