/* Generated by: FreeCC 0.9.3. Do not edit. JspDirective.java */
package org.owasp.orizon.mirage.jsp.parser;

public class JspDirective extends BaseNode {
    private String name;
    public String toString() {
        return super.toString()+" - "+getName();
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name=name;
    }

    public JspDirective(int id) {
        super(id);
    }

    public JspDirective() {
        super(JspConstants.JSPDIRECTIVE);
    }

}
