/* Generated by: FreeCC 0.9.3. Do not edit. JspDirectiveAttribute.java */
package org.owasp.orizon.mirage.jsp.parser;

public class JspDirectiveAttribute extends BaseNode {
    private String name;
    private String value;
    public String toString() {
        return super.toString()+" - "+getName();
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name=name;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value=value;
    }

    public JspDirectiveAttribute(int id) {
        super(id);
    }

    public JspDirectiveAttribute() {
        super(JspConstants.JSPDIRECTIVEATTRIBUTE);
    }

}
