/* Generated by: FreeCC 0.9.3. Do not edit. JspExpression.java */
package org.owasp.orizon.mirage.jsp.parser;

public class JspExpression extends BaseNode {
    private String image;
    public String toString() {
        return super.toString()+" - "+getImage();
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image=image;
    }

    public JspExpression(int id) {
        super(id);
    }

    public JspExpression() {
        super(JspConstants.JSPEXPRESSION);
    }

}
