/* Generated by: FreeCC 0.9.3. Do not edit. LST_ERROR.java */
package org.owasp.orizon.mirage.jsp.parser;

public class LST_ERROR extends Token {
    public LST_ERROR(int kind,String image) {
        super(kind,image);
    }

}
