/* Generated by: FreeCC 0.9.3. Do not edit. NAME.java */
package org.owasp.orizon.mirage.jsp.parser;

public class NAME extends Token {
    public NAME(int kind,String image) {
        super(kind,image);
    }

}
