/* Generated by: FreeCC 0.9.3. Do not edit. QUOTED_LITERAL.java */
package org.owasp.orizon.mirage.jsp.parser;

public class QUOTED_LITERAL extends Token {
    public QUOTED_LITERAL(int kind,String image) {
        super(kind,image);
    }

}
