/* Generated by: FreeCC 0.9.3. Do not edit. SINGLE_QUOTE.java */
package org.owasp.orizon.mirage.jsp.parser;

public class SINGLE_QUOTE extends Token {
    public SINGLE_QUOTE(int kind,String image) {
        super(kind,image);
    }

}
