/* Generated by: FreeCC 0.9.3. Do not edit. SYSTEM.java */
package org.owasp.orizon.mirage.jsp.parser;

public class SYSTEM extends Token {
    public SYSTEM(int kind,String image) {
        super(kind,image);
    }

}
