/* Generated by: FreeCC 0.9.3. Do not edit. TAG_SLASHEND.java */
package org.owasp.orizon.mirage.jsp.parser;

public class TAG_SLASHEND extends Token {
    public TAG_SLASHEND(int kind,String image) {
        super(kind,image);
    }

}
