/* Generated by: FreeCC 0.9.3. Do not edit. TAG_NAME.java */
package org.owasp.orizon.mirage.jsp.parser;

public class TAG_NAME extends Token {
    public TAG_NAME(int kind,String image) {
        super(kind,image);
    }

}
