/* Generated by: FreeCC 0.9.3. Do not edit. TAG_END.java */
package org.owasp.orizon.mirage.jsp.parser;

public class TAG_END extends Token {
    public TAG_END(int kind,String image) {
        super(kind,image);
    }

}
