/* Generated by: FreeCC 0.9.3. Do not edit. UNPARSED_TEXT_NO_SINGLE_QUOTES.java */
package org.owasp.orizon.mirage.jsp.parser;

public class UNPARSED_TEXT_NO_SINGLE_QUOTES extends Token {
    public UNPARSED_TEXT_NO_SINGLE_QUOTES(int kind,String image) {
        super(kind,image);
    }

}
