/* Generated by: FreeCC 0.9.3. Do not edit. UNPARSED_TEXT.java */
package org.owasp.orizon.mirage.jsp.parser;

public class UNPARSED_TEXT extends Token {
    public UNPARSED_TEXT(int kind,String image) {
        super(kind,image);
    }

}
