/* Generated by: FreeCC 0.9.3. Do not edit. UNPARSED.java */
package org.owasp.orizon.mirage.jsp.parser;

public class UNPARSED extends Token {
    public UNPARSED(int kind,String image) {
        super(kind,image);
    }

}
