/* Generated by: FreeCC 0.9.3. Do not edit. UnparsedText.java */
package org.owasp.orizon.mirage.jsp.parser;

public class UnparsedText extends BaseNode {
    private String image;
    public String toString() {
        return super.toString()+" - "+getImage();
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image=image;
    }

    public UnparsedText(int id) {
        super(id);
    }

    public UnparsedText() {
        super(JspConstants.UNPARSEDTEXT);
    }

}
