/* Generated by: FreeCC 0.9.3. Do not edit. VALUE_BINDING_IN_ATTRIBUTE.java */
package org.owasp.orizon.mirage.jsp.parser;

public class VALUE_BINDING_IN_ATTRIBUTE extends Token {
    public VALUE_BINDING_IN_ATTRIBUTE(int kind,String image) {
        super(kind,image);
    }

}
