/* Generated by: FreeCC 0.9.3. Do not edit. ValueBinding.java */
package org.owasp.orizon.mirage.jsp.parser;

public class ValueBinding extends BaseNode {
    private String image;
    public String toString() {
        return super.toString()+" - "+getImage();
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image=image;
    }

    public ValueBinding(int id) {
        super(id);
    }

    public ValueBinding() {
        super(JspConstants.VALUEBINDING);
    }

}
