/* Generated by: FreeCC 0.9.3. Do not edit. WHITESPACES.java */
package org.owasp.orizon.mirage.jsp.parser;

public class WHITESPACES extends Token {
    public WHITESPACES(int kind,String image) {
        super(kind,image);
    }

}
